import logging
import os

from rest_framework.decorators import api_view
from django.http import JsonResponse
from django.db import connection
from ..core.tasks import TASKS
from ..db import models
import psutil

logger = logging.getLogger(__name__)


_TASK_LOOKUP = {key: {
    "TASKTITLE": task.title,
    "DESCRIPTION": task.description,
    "shortTitle": task.shortTitle,
    "isAutogenerated": task.autogenerated,
} for key, task in TASKS.items()}


@api_view(["GET"])
def task_lookup(request):
    return JsonResponse(_TASK_LOOKUP)


@api_view(["GET"])
def active_jobs(request):
    """
    Returns a list of all running/queued jobs in the ccp4i2 job queue.

    Includes jobs that are RUNNING locally, RUNNING_REMOTELY on Azure workers,
    or QUEUED waiting for a worker to pick them up.
    """
    active_statuses = [
        models.Job.Status.RUNNING,
        models.Job.Status.RUNNING_REMOTELY,
        models.Job.Status.QUEUED,
    ]
    running_jobs = models.Job.objects.filter(status__in=active_statuses)
    active_jobs_list = []
    for job in running_jobs:
        pid = job.process_id
        cpu_percent = None
        mem_usage = None

        # Try to get process metrics if we have a local PID
        if pid:
            try:
                proc = psutil.Process(pid)

                def get_total_cpu_percent(process):
                    try:
                        process.cpu_percent(interval=None)
                        children = process.children(recursive=True)
                        for child in children:
                            child.cpu_percent(interval=None)
                        total_cpu = process.cpu_percent(interval=0.5)
                        for child in children:
                            total_cpu += get_total_cpu_percent(child)
                        return total_cpu
                    except (psutil.NoSuchProcess, psutil.AccessDenied):
                        return 0.0

                cpu_percent = get_total_cpu_percent(proc)
                mem_info = proc.memory_info()
                mem_usage = mem_info.rss
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                pass

        active_jobs_list.append(
            {
                "project": job.project.name,
                "job_id": job.pk,
                "job_task_name": job.task_name,
                "job_uuid": job.uuid,
                "job_number": job.number,
                "status": job.get_status_display(),
                "pid": pid,
                "cpu_percent": cpu_percent,
                "memory_usage_bytes": mem_usage,
            }
        )
    return JsonResponse({"success": True, "data": {"active_jobs": active_jobs_list}})


def health_check(request):
    """
    Simple health check endpoint for deployment monitoring.
    Returns 200 OK if the service is healthy.
    """
    try:
        # Test database connection
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1")

        return JsonResponse(
            {
                "status": "healthy",
                "service": "ccp4i2-django-api",
                "database": "connected",
            }
        )
    except Exception as e:
        return JsonResponse(
            {
                "status": "unhealthy",
                "service": "ccp4i2-django-api",
                "database": "disconnected",
                "error": str(e),
            },
            status=503,
        )


def version_info(request):
    """
    Returns version information for the server deployment.
    Build timestamp and git commit are set via environment variables during Docker build.
    """
    return JsonResponse(
        {
            "buildTimestamp": os.environ.get("BUILD_TIMESTAMP", "dev"),
            "gitCommit": os.environ.get("GIT_COMMIT", "unknown"),
        }
    )


@api_view(["GET"])
def monomer_info(request, code):
    """
    Return atom and bond information for a CCP4 monomer library entry.

    GET /api/ccp4i2/monomer-info/<code>/

    Response:
    {
        "success": true,
        "data": {
            "code": "LYS",
            "atoms": ["N", "CA", "C", "O", "CB", ...],
            "bonds": [
                {"atom1": "N", "atom2": "CA", "type": "single"},
                ...
            ]
        }
    }
    """
    from ..lib.utils.formats.cif_ligand import extract_monomer_atoms_bonds

    ccp4 = os.environ.get("CCP4", "")
    if not ccp4:
        return JsonResponse(
            {"success": False, "error": "CCP4 environment not configured"},
            status=500,
        )

    # Monomer library: $CCP4/lib/data/monomers/{first_letter}/{CODE}.cif
    code_upper = code.upper()
    first_letter = code_upper[0].lower()
    cif_path = os.path.join(ccp4, "lib", "data", "monomers", first_letter, f"{code_upper}.cif")

    if not os.path.isfile(cif_path):
        return JsonResponse(
            {"success": False, "error": f"Monomer '{code_upper}' not found in library"},
            status=404,
        )

    try:
        result = extract_monomer_atoms_bonds(cif_path)
        return JsonResponse({
            "success": True,
            "data": {
                "code": code_upper,
                "atoms": result["atoms"],
                "bonds": result["bonds"],
            },
        })
    except Exception as e:
        logger.exception("Error parsing monomer CIF for %s", code_upper)
        return JsonResponse(
            {"success": False, "error": f"Error parsing monomer: {str(e)}"},
            status=500,
        )


# ---------------------------------------------------------------------------
# Program locations (binary discovery) preferences
# ---------------------------------------------------------------------------

# The userPreferences keys the Program-locations UI reads/writes. Kept explicit
# so the write endpoint can reject anything else (it must not become a general
# preferences-write backdoor).
_PROGRAM_PREF_KEYS = (
    "exePaths",
    "COOT_EXECUTABLE",
    "CCP4MG_EXECUTABLE",
    "SHELXDIR",
    "DIALSDIR",
    "BUSTERDIR",
)


# Executables that are core CCP4/Python interpreters or ubiquitous utilities:
# always present, not user-relocatable, and noise in a "point me at your
# programs" panel. Excluded from the default discovery list (still probeable
# explicitly via ?names=).
_DISCOVERY_EXCLUDE = frozenset({
    "ccp4-python", "python", "python3", "cad", "gemmi", "pdbset", "mtzutils",
    "cif2mtz", "convert2mtz", "chltofom", "cmapcoeff",
})


@api_view(["GET"])
def discover_programs_view(request):
    """Report where each task program resolves (read-only probe).

    GET /api/ccp4i2/config/discover-programs/[?names=cbuccaneer,shelxd]

    The default program set is the registry-derived list of distinct plugin
    TASKCOMMANDs — the real executables the task suite runs (correct names, e.g.
    ``cbuccaneer`` not ``buccaneer``), each annotated with the tasks that need
    it. Pass ``names`` to probe a specific set instead. Core interpreters /
    ubiquitous utilities are omitted from the default list.

    Response: {"success": true, "data": {"programs": [
        {"name", "path"|null, "source": ..., "tasks": [task_name, ...]}
    ]}}
    Never runs a program; just resolves paths against preferences + PATH.
    """
    from ..config.program_discovery import discover_program
    from ..core.tasks import task_commands

    names_param = request.query_params.get("names")
    cmd_map = task_commands()
    if names_param:
        names = [n.strip() for n in names_param.split(",") if n.strip()]
    else:
        # Registry-derived defaults: real executable names, minus core/noise and
        # anything that is an absolute path or a dotted sub-tool wrapper we can't
        # meaningfully "relocate" (kept if a plain command name).
        names = [
            cmd
            for cmd in cmd_map
            if cmd not in _DISCOVERY_EXCLUDE and "/" not in cmd
        ]

    programs = []
    for name in names:
        entry = discover_program(name)
        entry["tasks"] = cmd_map.get(name, [])
        programs.append(entry)
    return JsonResponse({"success": True, "data": {"programs": programs}})


@api_view(["GET"])
def get_program_preferences(request):
    """Return the current program-location preferences + desktop-writability.

    GET /api/ccp4i2/config/program-preferences/

    Response: {"success": true, "data": {"editable": <bool>, "preferences": {...}}}
    In cloud (`editable=false`) these come from env vars and are not file-editable.
    """
    from ..config.preferences import is_desktop, load_preferences

    # First-load lazy migration: import program locations from the legacy Qt GUI
    # (~/.CCP4I2). Desktop-only and idempotent (self-guarded), so calling it here
    # is safe and cheap — it no-ops in cloud and after the first successful run.
    try:
        from ..config.preferences_migration import migrate_legacy_program_prefs

        migrate_legacy_program_prefs()
    except Exception:
        logger.debug("legacy program-preference migration skipped", exc_info=True)

    bag = load_preferences().get("userPreferences", {})
    bag = bag if isinstance(bag, dict) else {}
    prefs = {k: bag[k] for k in _PROGRAM_PREF_KEYS if k in bag}
    return JsonResponse(
        {"success": True, "data": {"editable": is_desktop(), "preferences": prefs}}
    )


@api_view(["PATCH", "POST"])
def set_program_preferences(request):
    """Update program-location preferences (desktop only).

    PATCH /api/ccp4i2/config/program-preferences/  {"SHELXDIR": "...", "exePaths": [...]}

    Only the _PROGRAM_PREF_KEYS are accepted; any other key is ignored. In a
    cloud deployment this is rejected (409) — preferences arrive as env vars and
    preferences.json is per-replica/ephemeral.
    """
    from ..config.preferences import is_desktop, load_preferences, save_preferences

    if not is_desktop():
        return JsonResponse(
            {
                "success": False,
                "error": "Program-location preferences are editable only on the "
                "desktop app; in a server deployment set them via environment "
                "variables.",
            },
            status=409,
        )

    payload = request.data if isinstance(request.data, dict) else {}
    updates = {k: v for k, v in payload.items() if k in _PROGRAM_PREF_KEYS}

    prefs = load_preferences()
    bag = prefs.get("userPreferences")
    bag = bag if isinstance(bag, dict) else {}
    for key, value in updates.items():
        if value in (None, "", []):
            bag.pop(key, None)  # clearing a field removes it
        else:
            bag[key] = value
    prefs["userPreferences"] = bag
    save_preferences(prefs)

    saved = {k: bag[k] for k in _PROGRAM_PREF_KEYS if k in bag}
    return JsonResponse({"success": True, "data": {"preferences": saved}})


# ---------------------------------------------------------------------------
# Tips of the Day
# ---------------------------------------------------------------------------

# Deterministic-free randomness for tip selection; tips live beside the package.
_TIPS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "tipsOfTheDay")


def _tip_ids():
    try:
        return sorted(
            int(f[:-5])
            for f in os.listdir(_TIPS_DIR)
            if f.endswith(".html") and f[:-5].isdigit()
        )
    except OSError:
        return []


@api_view(["GET"])
def tip_of_the_day(request):
    """Return a random (or specific) tip's body HTML.

    GET /api/ccp4i2/tips/?id=<n>   (id optional; omitted -> random)

    Response: {"success": true, "data": {"id": <n>, "html": "<...>", "count": <N>}}
    Image ``src="./foo.png"`` references are rewritten to the tip-image route so
    they render in the app.
    """
    import random
    import re

    ids = _tip_ids()
    if not ids:
        return JsonResponse(
            {"success": False, "error": "No tips available"}, status=404
        )

    requested = request.query_params.get("id")
    if requested is not None and requested.isdigit() and int(requested) in ids:
        tip_id = int(requested)
    else:
        tip_id = random.choice(ids)

    path = os.path.join(_TIPS_DIR, f"{tip_id}.html")
    try:
        with open(path, encoding="windows-1252") as handle:
            raw = handle.read()
    except OSError:
        return JsonResponse(
            {"success": False, "error": f"Tip {tip_id} not found"}, status=404
        )

    # Extract the <body> inner HTML (the tips are full HTML documents).
    body_match = re.search(r"<body[^>]*>(.*)</body>", raw, re.DOTALL | re.IGNORECASE)
    html = body_match.group(1).strip() if body_match else raw
    # Rewrite relative image srcs to the tip-image API route.
    html = re.sub(
        r'src\s*=\s*["\']\.?/?([^"\']+\.(?:png|jpg|jpeg|gif))["\']',
        lambda m: f'src="/api/proxy/ccp4i2/tips/image/{m.group(1)}"',
        html,
        flags=re.IGNORECASE,
    )
    return JsonResponse(
        {"success": True, "data": {"id": tip_id, "html": html, "count": len(ids)}}
    )


@api_view(["GET"])
def tip_image(request, name):
    """Serve a tip image by filename (from the tipsOfTheDay dir only)."""
    from django.http import FileResponse, Http404

    # Guard against path traversal: basename only, must live in the tips dir.
    safe = os.path.basename(name)
    path = os.path.join(_TIPS_DIR, safe)
    if not os.path.isfile(path):
        raise Http404("Tip image not found")
    return FileResponse(open(path, "rb"))
