TITLES = {
    "AUSPEX": "AUSPEX",
    "Lidia": "Lidia",
    "TestObsConversions": "TestObsConversions",
    "acedrg": "acedrg",
    "acedrgNew": "acedrgNew",
    "acorn": "Acorn",
    "add_fractional_coords": "Add Fractional Coordinates",
    "aimless": "Scale and merge dataset (AIMLESS)",
    "aimless_pipe": "Scale and merge data",
    "arcimboldo": "Arcimboldo",
    "arp_warp_classic": "ARP/WARP classic",
    "baverage": "Average B over main and side chain atoms",
    "buster": "Refinement with Buster (Global Phasing Limited)",
    "cad_copy_column": "Copy an MTZ column between files",
    "ccp4mg_edit_model": "Interactive model preparation - CCP4mg and MrBUMP",
    "ccp4mg_edit_nomrbump": "Interactive selection of MR model components - CCP4mg",
    "ccp4mg_general": "Molecular graphics visualization and figure creation - CCP4MG",
    "chainsaw": "edit search model",
    "cif2mtz": "Import mmCIF reflection file",
    "clustalw": "clustalw",
    "cmapcoeff": "Prepare map coefficients",
    "convert2mtz": "Convert merged reflection file to MTZ",
    "coordinate_selector": "Select subset from coordinates",
    "coot1": "Coot 1",
    "coot_find_ligand": "Find ligand with Coot API",
    "coot_find_waters": "Find waters with Coot API",
    "coot_rebuild": "Rebuild model with coot",
    "coot_rsr_morph": "Real space refinement morphing with Coot API",
    "coot_script_lines": "Execute arbitrary script code within Coot",
    "cpatterson": "Prepare map coefficients",
    "cphasematch": "Match and analyse phases to reference set",
    "crank2": "Crank2",
    "crank2_comb_phdmmb": "Crank2",
    "crank2_dmfull": "Crank2",
    "crank2_faest": "Crank2",
    "crank2_handdet": "Crank2",
    "crank2_mbref": "Crank2",
    "crank2_phas": "Crank2",
    "crank2_phdmmb": "Crank2",
    "crank2_ref": "Crank2",
    "crank2_refatompick": "Crank2",
    "crank2_substrdet": "Crank2",
    "csymmatch": "Csymmatch - move model to a reference by using symmetry",
    "ctruncate": "Intensities to amplitudes",
    "density_calculator": "Density Calculator",
    "dials_image": "Dials_image",
    "dials_rlattice": "Dials_rLattice",
    "dui": "Integrate images - DIALS",
    "editbfac": "Process Predicted Models",
    "edstats": "Measure agreement between model and density",
    "fft": "Export map",
    "findmyseq": "Find My Sequence",
    "freerflag": "Add a freeR flag",
    "gesamt": "Gesamt - structural alignment",
    "imosflm": "Integrate images - iMosflm",
    "import_serial": "Import Serial Core",
    "import_serial_pipe": "Import Serial Pipeline",
    "import_xia2": "Import XIA2 results",
    "mergeMtz": "Merge experimental data objects to MTZ",
    "modelcraft": "AutoBuild with ModelCraft, Buccaneer and Nautilus",
    "molrep_den": "Molecular replacement with electron density - MOLREP",
    "molrep_mr": "Molecular replacement using Molrep",
    "molrep_selfrot": "Molecular replacement using Molrep",
    "mosflm": "Run mosflm and capture output",
    "mrbump_basic": "MrBUMP Basic",
    "mrbump_model_prep": "MrBUMP model preparation",
    "mrparse": "mrparse",
    "mrparse_simple": "mrparse_simple",
    "mtzheader": "Read MTZ header",
    "mtzutils": "Add or delete MTZ columns",
    "pairef": "Pairef",
    "parrot": "Parrot",
    "pdb_extract_wrapper": "pdb_extract_wrapper",
    "pdb_redo_api": "PDB-REDO Web services",
    "pdbset_ui": "Scripted structure edits - Pdbset",
    "pdbview_edit": "Edit PDB/CIF files by hand with the PdbView program",
    "phaser_MR_FRF": "Rotation function - PHASER",
    "phaser_MR_FTF": "Translation function - PHASER",
    "phaser_MR_PAK": "Packing function - PHASER",
    "phaser_analysis": "phaser_analysis",
    "phaser_singleMR": "Single Atom MR",
    "pisa_analyse": "Structure analysis with Pisa",
    "pisa_list": "Structure analysis with Pisa",
    "pisa_xml": "Structure analysis with Pisa",
    "pisapipe": " Structure analysis with Pisa",
    "pointless": "Analyse unmerged dataset (POINTLESS)",
    "prosmart_refmac": "Refine with Refmac & optional restraints from Prosmart & Platonyzer",
    "pyphaser_mr": "MR using Phaser (pythonic)",
    "qtpisa": "Analyze bilogical units with qtpisa",
    "refmac": "Refinement (Refmac5)",
    "scaleit": "Compare two or more datafiles",
    "scalepack2mtz": "Convert scalepack merged reflection file to MTZ",
    "sculptor": "Truncate search model - SCULPTOR",
    "servalcat": "Refinement (servalcat)",
    "servalcat_pipe": "Refinement against diffraction data with optional restraints (ProSMART, MetalCoord)",
    "shelx": "SHELX",
    "shelxeMR": "ShelxeMR",
    "slicendice": "SliceNDice",
    "splitMtz": "Import and Split MTZ to experimental data objects",
    "tableone": "Generate Table One",
    "xia2_aimless": "Aimless in XIA2",
    "xia2_ctruncate": "CTruncate in XIA2",
    "xia2_dials": "Data processing with xia2/dials",
    "xia2_integration": "Integration in XIA2",
    "xia2_multiplex": "Data set combination with xia2.multiplex",
    "xia2_pointless": "Pointless in XIA2",
    "xia2_run": "Import data processing results from XIA2",
    "xia2_ssx_reduce": "Reduction of serial datasets using xia2.ssx_reduce",
    "xia2_xds": "Data processing with xia2/xds",
    "zanuda": "Zanuda",
}
