REPORTS = {
    "AMPLE": {"RUNNING": True},
    "Acedrg": {"RUNNING": True},
    "AlternativeImportXIA2": {"RUNNING": True},
    "LidiaAcedrgNew": {"RUNNING": True},
    "MakeProjectsAndDoLigandPipeline": {"RUNNING": True},
    "PrepareDeposit": {"RUNNING": True},
    "RvapiReport": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "SIMBAD": {"RUNNING": True},
    "ShelxCD": {"RUNNING": True},
    "SubstituteLigand": {"RUNNING": True},
    "add_fractional_coords": {"RUNNING": True},
    "adding_stats_to_mmcif_i2": {"RUNNING": True},
    "arcimboldo": {"RUNNING": True, "WATCHED_FILE": "program.xml"},
    "arp_warp_classic": {"RUNNING": True, "WATCHED_FILE": "report/task.tsk"},
    "crank2": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_comb_phdmmb": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_dmfull": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_faest": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_handdet": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_mbref": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_phas": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_phdmmb": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_ref": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_refatompick": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "crank2_substrdet": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "dr_mr_modelbuild_pipeline": {"RUNNING": True},
    "import_merged": {"RUNNING": True},
    "import_xia2": {"RUNNING": True},
    "lorestr_i2": {"RUNNING": True},
    "metalCoord": {"RUNNING": True},
    "modelcraft": {"RUNNING": True, "WATCHED_FILE": "modelcraft/modelcraft.json"},
    "molrep_pipe": {"RUNNING": True},
    "morda_i2": {"RUNNING": True, "WATCHED_FILE": "program.xml"},
    "mosflm": {"RUNNING": True},
    "mrbump_basic": {"RUNNING": True},
    "pairef": {"RUNNING": True, "WATCHED_FILE": "pairef_project/PAIREF_project.html"},
    "pdb_redo_api": {"RUNNING": True},
    "phaser_EP": {"RUNNING": True},
    "phaser_EP_AUTO": {"RUNNING": True},
    "phaser_EP_LLG": {"RUNNING": True},
    "phaser_MR_AUTO": {"RUNNING": True},
    "phaser_MR_FRF": {"RUNNING": True},
    "phaser_MR_FTF": {"RUNNING": True},
    "phaser_MR_RNP": {"RUNNING": True},
    "phaser_pipeline": {"RUNNING": True},
    "phaser_rnp_pipeline": {"RUNNING": True},
    "phaser_simple": {"RUNNING": True},
    "pisa_xml": {"RUNNING": True},
    "pisapipe": {"RUNNING": True},
    "prosmart_refmac": {"RUNNING": True},
    "pyphaser_mr": {"RUNNING": True},
    "refmac": {"RUNNING": True},
    "scaleit": {"RUNNING": True},
    "servalcat": {"RUNNING": True},
    "servalcat_pipe": {"RUNNING": True},
    "shelx": {"RUNNING": True, "WATCHED_FILE": "i2.xml"},
    "shelxeMR": {"RUNNING": True},
    "slicendice": {"RUNNING": True},
    "xia2_dials": {"RUNNING": True},
    "xia2_multiplex": {"RUNNING": True},
    "xia2_ssx_reduce": {"RUNNING": True},
    "xia2_xds": {"RUNNING": True},
    "zanuda": {"RUNNING": True, "WATCHED_FILE": "log.txt"},
}
