/**
 * Does each task interface actually let a user reach the task's parameters?
 *
 * Nothing tested this before. The i2run suite drives tasks through the CLI and
 * the api/e2e suite through REST, so both prove the *backend* works while
 * saying nothing about the React form in front of it. That is how
 * `arp_warp_classic` came to ship as two empty accordions over a 47-parameter
 * def.xml without any tier noticing.
 *
 * The declared side comes from `fixtures/task-parameters.json`, written by
 * `manage.py dump_task_parameters` using the server's own def.xml loader (so
 * composed definitions such as servalcat_pipe -> servalcat resolve properly).
 * The exposed side is read straight out of the `.tsx` files here. No Python, no
 * CCP4, no database: this runs in the CCP4-free job.
 *
 * The bar is Qt, not the def.xml. crank2 declares 238 parameters and its Qt GUI
 * exposed 111 -- a def.xml is a superset of what any sane form shows, so "100%
 * of declared" is not the goal and never was. What a user could reach in the
 * released Qt application is the goal, and `qtExposed` in the fixture records
 * it.
 *
 * Counting named parameters alone would libel both sides, because both have a
 * way of rendering a container's whole contents without naming anything in it.
 * Here, a `<CCP4i2ContainerElement itemName="X" />` with no JSX children falls
 * through to `ccontainer.tsx`'s auto-layout and shows every child of X; six
 * interfaces are built that way, and scanning for `itemName="..."` would score
 * them near zero. Qt's equivalent is `autoGenerate`, which the fixture already
 * resolves. Miss either and the comparison silently comes out even.
 *
 * This is a ratchet, not a pass/fail line. `baselines/task-coverage.json` holds
 * today's gap for each task; the test fails when a gap grows, and tells you to
 * regenerate when one shrinks. Regenerate with:
 *
 *     UPDATE_COVERAGE_BASELINE=1 npx vitest run task-parameter-coverage
 */
import { describe, it, expect } from "vitest";
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "fs";
import path from "path";

const HERE = __dirname;
const INTERFACE_DIR = path.resolve(HERE, "../components/task/task-interfaces");
const FIXTURE = path.join(HERE, "fixtures", "task-parameters.json");
const BASELINE = path.join(HERE, "baselines", "task-coverage.json");
const EXCLUSIONS = path.join(HERE, "coverage-exclusions.json");
const UPDATING = process.env.UPDATE_COVERAGE_BASELINE === "1";

interface TaskParameters {
  /** Declared parameter paths, by root container ("inputData", "keywords", ...). */
  declared: Record<string, string[]>;
  /** Output files: not part of the coverage maths, but legal to render. */
  outputData?: string[];
  /**
   * The task's `guiParameters` container. Not counted, because it is mostly
   * rendering state (`OPEN_*` subframe toggles, `EXPERT_LEVEL`) that React
   * expresses as a `visibility` prop and rightly has no field for -- but it
   * also holds real user controls (`ProvideTLS.EDIT_MODE`,
   * `molrep_*.PERFORM`, `mrbump_basic.USE_FIXED`), so an interface naming one
   * is not naming a phantom. The container's purpose is not pure either way,
   * so neither counting it nor ignoring it would be honest.
   */
  guiParameters?: string[];
  /** Parameters come from a PHIL tree at runtime, so the def.xml lists few. */
  philDriven?: boolean;
  qtExposed?: string[];
  /** Qt drew part of this task with `autoGenerate`. */
  qtAutoGenerated?: boolean;
  /** ...and at least one such call could not be resolved statically, so
   *  `qtExposed` is a floor rather than the full picture. */
  qtExposedIncomplete?: boolean;
}

const fixture: { tasks: Record<string, TaskParameters> } = JSON.parse(
  readFileSync(FIXTURE, "utf8")
);

/** Task name -> interface module path, read from the registry itself. */
function interfaceRegistry(): Record<string, string> {
  const source = readFileSync(path.join(INTERFACE_DIR, "task-container.tsx"), "utf8");
  const imports: Record<string, string> = {};
  for (const m of source.matchAll(/import\s+(\w+)\s+from\s+"\.\/([^"]+)"/g)) {
    imports[m[1]] = m[2];
  }
  const body = source.split("const TASK_INTERFACES")[1]?.split("};")[0] ?? "";
  const registry: Record<string, string> = {};
  for (const m of body.matchAll(/^\s*([A-Za-z0-9_]+):\s*(\w+),/gm)) {
    const module = imports[m[2]];
    if (module) registry[m[1]] = module;
  }
  return registry;
}

/** Every .tsx making up one interface -- some are a directory of tab files. */
function interfaceFiles(module: string): string[] {
  const asDir = path.join(INTERFACE_DIR, module);
  if (existsSync(asDir) && statSync(asDir).isDirectory()) {
    const out: string[] = [];
    const walk = (dir: string) => {
      for (const entry of readdirSync(dir)) {
        const full = path.join(dir, entry);
        if (statSync(full).isDirectory()) walk(full);
        else if (entry.endsWith(".tsx")) out.push(full);
      }
    };
    walk(asDir);
    return out;
  }
  const asFile = `${asDir}.tsx`;
  return existsSync(asFile) ? [asFile] : [];
}

interface Exposure {
  names: Set<string>;
  /** Containers rendered whole by `ccontainer.tsx`'s auto-layout. */
  autoRendered: Set<string>;
  /** Names subtracted from an auto-rendered container by `excludeItems`. */
  excluded: Set<string>;
  /**
   * Literal prefixes of indexed families, from ``itemName={`ACOPH_DDMK_${n}`}``.
   * acorn, crank2 and metalCoord render numbered parameter families in a loop,
   * so the individual names never appear -- but the prefix does, and every
   * declared parameter starting with it is reachable.
   */
  prefixes: string[];
  /** A computed `itemName` that is neither of the two readable idioms. */
  dynamic: boolean;
}

/**
 * A `<CCP4i2ContainerElement>` with no JSX children, and the attribute text of
 * each. `ccontainer.tsx` renders `children` when given any and falls back to
 * laying out the container's own contents when not, so a self-closing tag is
 * the "render everything under here" idiom.
 */
function selfClosingContainers(source: string): string[] {
  const attributes: string[] = [];
  for (const m of source.matchAll(
    /<CCP4i2ContainerElement\b((?:[^<>]|\{[^{}]*\})*?)\/>/g
  )) {
    attributes.push(m[1]);
  }
  return attributes;
}

function exposedParameters(module: string): Exposure {
  const source = interfaceFiles(module)
    .map((f) => readFileSync(f, "utf8"))
    .join("\n");

  const names = new Set<string>();
  for (const m of source.matchAll(/itemName=["']([A-Za-z_][\w.]*)["']/g)) names.add(m[1]);
  for (const m of source.matchAll(/useTaskItem\(\s*["']([A-Za-z_][\w.]*)["']/g)) names.add(m[1]);
  // The config-array idiom: a list of `{ key: "RESO_LOW", label: ... }` mapped
  // to elements with `itemName={key}`. Object-literal `key:` only -- the JSX
  // attribute `key="..."` is React's list key and names no parameter.
  for (const m of source.matchAll(/\bkey:\s*["']([A-Za-z_][\w.]*)["']/g)) names.add(m[1]);

  const prefixes: string[] = [];
  for (const m of source.matchAll(/itemName=\{\s*`([A-Za-z_][\w.]*)\$\{/g)) {
    prefixes.push(m[1]);
  }

  const autoRendered = new Set<string>();
  const excluded = new Set<string>();
  for (const attributes of selfClosingContainers(source)) {
    const named = /itemName=["']([A-Za-z_][\w.]*)["']/.exec(attributes);
    if (!named) continue;
    autoRendered.add(named[1]);
    const excludes = /excludeItems=\{\s*\[([^\]]*)\]/.exec(attributes);
    if (excludes) {
      for (const e of excludes[1].matchAll(/["']([\w.]+)["']/g)) excluded.add(e[1]);
    }
  }

  // Anything else computed: not `{key}` from a config array, not a template
  // literal whose prefix we captured.
  const unreadable = [...source.matchAll(/itemName=\{([^}]*)\}/g)].some(
    (m) => !/^\s*key\s*$/.test(m[1]) && !/^\s*`[A-Za-z_][\w.]*\$\{/.test(m[1])
  );

  return { names, autoRendered, excluded, prefixes, dynamic: unreadable };
}

/**
 * Leaf names that denote more than one declared parameter in this task.
 *
 * `prosmartProtein.RMAX` and `prosmartNucleicAcid.RMAX` are two different
 * restraint limits, one per chain type; `libg.TOGGLE`, `platonyzer.TOGGLE` and
 * both prosmart TOGGLEs are four unrelated switches. Matching such a parameter
 * on its last segment alone would let one field stand in for all of them --
 * 93 declared parameters across prosmart_refmac and servalcat_pipe sit under
 * an ambiguous leaf, and those are exactly the two interfaces where a shared
 * protein/nucleic-acid component is worth extracting. The check has to be
 * strictest where that refactor would be riskiest, not blindest.
 */
function ambiguousLeaves(parameters: TaskParameters): Set<string> {
  const counts = new Map<string, number>();
  for (const paths of Object.values(parameters.declared)) {
    for (const p of paths) {
      const leaf = p.split(".").pop()!;
      counts.set(leaf, (counts.get(leaf) ?? 0) + 1);
    }
  }
  return new Set([...counts].filter(([, n]) => n > 1).map(([leaf]) => leaf));
}

/**
 * Is *parameter*, declared in root container *section*, reachable in the form?
 *
 * Either the interface names it -- or names its last dotted segment, since
 * `metalCoordWrapper.SIMPLE` is often just `SIMPLE` in the form and both
 * address the same field -- or an ancestor of it is auto-rendered whole.
 *
 * That last-segment shortcut is withdrawn for a leaf the task uses more than
 * once: there, the interface must name enough of the path to say which
 * parameter it means. (The phaser tasks looked far worse, 126 ambiguous leaves
 * apiece, until the fixture stopped counting the def.xml parser's phantom root
 * scopes; every one of those was a parameter counted twice rather than two
 * parameters.)
 *
 * Note for phaser work: a keyword scope's ids are phaser's own four-character
 * contractions, generated by `create_def_xml.py: make_keyword()` taking the
 * first four characters of each token in the PHIL path. So a task can declare
 * both `inputData.RESOLUTION_HIGH` and `keywords.resolution.RESO_HIGH`, and
 * they are different parameters. Copying a long name from one phaser interface
 * into another that only has the contraction gives a field that silently sets
 * nothing -- which is how `SGALT_SELECT` came to be dead in
 * phaser_rnp_pipeline. The phantom check catches this.
 */
function reachable(
  parameter: string,
  section: string,
  exposure: Exposure,
  ambiguous: Set<string>
): boolean {
  const leaf = parameter.split(".").pop()!;

  if (exposure.names.has(parameter)) return true;

  if (ambiguous.has(leaf)) {
    // Needs enough of the path to disambiguate: `prosmartProtein.RMAX`, not
    // `RMAX`. Declared paths are relative to their section, so qualify with it
    // -- the refinement weight is section `controlParameters`, path `WEIGHT`,
    // and the interface writes it `controlParameters.WEIGHT`. Then compare from
    // the right, since an interface may give any sufficient suffix.
    const wanted = [...section.split("."), ...parameter.split(".")];
    for (const name of exposure.names) {
      const got = name.split(".");
      if (got.length < 2 || got.length > wanted.length) continue;
      const tail = wanted.slice(-got.length);
      if (tail.every((s, i) => s === got[i])) return true;
    }
  } else {
    for (const name of exposure.names) {
      if (name === leaf || name.split(".").pop() === leaf) return true;
    }
    if (exposure.prefixes.some((p) => leaf.startsWith(p))) return true;
  }

  // The whole section, or some container on the way down to this parameter.
  // `excludeItems` subtracts from what an auto-rendered container lays out --
  // it says nothing about a field named explicitly elsewhere. ShelxCD renders
  // MODE, FIND, NTRY and SFAC by hand on its first tab and excludes them from
  // the auto-generated Keywords tab, exactly as Qt does; reading the exclusion
  // as a blanket suppression would call all four unreachable.
  if (exposure.excluded.has(leaf) || exposure.excluded.has(parameter)) {
    return false;
  }
  if (exposure.autoRendered.has(section)) return true;
  const segments = parameter.split(".");
  for (let i = 1; i < segments.length; i++) {
    const ancestor = segments.slice(0, i).join(".");
    if (exposure.autoRendered.has(ancestor) || exposure.autoRendered.has(`${section}.${ancestor}`)) {
      return true;
    }
  }
  return false;
}

const registry = interfaceRegistry();

/** Which root container each declared parameter path belongs to. */
function sectionOf(parameters: TaskParameters): Map<string, string> {
  const sections = new Map<string, string>();
  for (const [section, paths] of Object.entries(parameters.declared)) {
    for (const path of paths) sections.set(path, section);
  }
  return sections;
}

interface ExclusionGroup {
  reason: string[];
  parameters: string[];
}

/**
 * Parameters we have decided not to expose, by task.
 *
 * Hand-maintained in `coverage-exclusions.json` and never regenerated, because
 * each is a judgement rather than a measurement. Kept out of `gaps` so that a
 * question someone has closed does not look like work outstanding -- if the two
 * were mixed, a falling gap count would stop distinguishing "we built it" from
 * "we talked ourselves out of it".
 */
function exclusions(): Record<string, Set<string>> {
  const raw: Record<string, ExclusionGroup[] | unknown> = JSON.parse(
    readFileSync(EXCLUSIONS, "utf8")
  );
  const byTask: Record<string, Set<string>> = {};
  for (const [task, groups] of Object.entries(raw)) {
    if (task.startsWith("_") || !Array.isArray(groups)) continue;
    byTask[task] = new Set(
      (groups as ExclusionGroup[]).flatMap((group) => group.parameters)
    );
  }
  return byTask;
}

const excluded = exclusions();

/** Qt-exposed parameters this interface cannot reach, per task. */
function currentGaps(): Record<string, string[]> {
  const gaps: Record<string, string[]> = {};
  for (const [task, module] of Object.entries(registry)) {
    const parameters = fixture.tasks[task];
    if (!parameters?.qtExposed) continue;
    const exposure = exposedParameters(module);
    if (exposure.dynamic) continue;
    // Only hold the interface to parameters the task still declares: the Qt
    // GUI may name fields that have since been renamed or removed.
    const sections = sectionOf(parameters);
    const ambiguous = ambiguousLeaves(parameters);
    const decided = excluded[task] ?? new Set<string>();
    const missing = parameters.qtExposed
      .filter(
        (p) =>
          sections.has(p) &&
          !decided.has(p) &&
          !reachable(p, sections.get(p)!, exposure, ambiguous)
      )
      .sort();
    if (missing.length) gaps[task] = missing;
  }
  return gaps;
}

/**
 * `itemName` values that name nothing the task declares, per task.
 *
 * prosmart shipped with itemName="Target", "Reference" and "Fragment library" --
 * the guiLabels out of the Qt `createLine(['widget', '-guiLabel', 'Target',
 * 'XYZIN'])`, not the parameter names. `useTaskItem` returns a null item for a
 * name that is not in the container, so each of those fields rendered nothing at
 * all, silently. Three of that interface's four fields were dead.
 */
function currentPhantoms(): Record<string, string[]> {
  const phantom: Record<string, string[]> = {};
  for (const [task, module] of Object.entries(registry)) {
    const parameters = fixture.tasks[task];
    if (!parameters || parameters.philDriven) continue;

    const known = new Set<string>();
    const remember = (section: string, p: string) => {
      known.add(p);
      known.add(p.split(".").pop()!);
      known.add(`${section}.${p}`);
    };
    for (const [section, paths] of Object.entries(parameters.declared)) {
      known.add(section);
      for (const p of paths) remember(section, p);
    }
    for (const section of ["outputData", "guiParameters"] as const) {
      known.add(section);
      for (const p of parameters[section] ?? []) remember(section, p);
    }

    const exposure = exposedParameters(module);
    const unknown = [...exposure.names]
      .filter((n) => !known.has(n) && !known.has(n.split(".").pop()!))
      .sort();
    if (unknown.length) phantom[task] = unknown;
  }
  return phantom;
}

/**
 * Every declared parameter an interface can currently reach, per task.
 *
 * The gaps ratchet watches only parameters the Qt GUI exposed, which turns out
 * to be a narrow window: of prosmart_refmac's 36 `prosmart*` parameters it
 * watches 2, and of servalcat_pipe's 39 it watches 1, because those pipelines
 * embed a bespoke prosmart container whose names Qt's GUI never used. Anything
 * this codebase added since the Qt era is unwatched for the same reason.
 *
 * So this records what is reachable *now*, whatever its provenance, and the
 * check below fails if a parameter stops being reachable. That is the guard
 * that makes a refactor safe -- extracting one shared component for the
 * protein and nucleic-acid restraint blocks, say, where dropping
 * `prosmartNucleicAcid.RMAX` would otherwise show up as nothing at all.
 */
function currentlyReachable(): Record<string, string[]> {
  const reached: Record<string, string[]> = {};
  for (const [task, module] of Object.entries(registry)) {
    const parameters = fixture.tasks[task];
    if (!parameters || parameters.philDriven) continue;
    const exposure = exposedParameters(module);
    if (exposure.dynamic) continue;
    const ambiguous = ambiguousLeaves(parameters);
    const hits: string[] = [];
    for (const [section, paths] of Object.entries(parameters.declared)) {
      for (const p of paths) {
        if (reachable(p, section, exposure, ambiguous)) hits.push(`${section}.${p}`);
      }
    }
    if (hits.length) reached[task] = hits.sort();
  }
  return reached;
}

interface Baseline {
  /** Qt-exposed parameters an interface cannot reach. */
  gaps: Record<string, string[]>;
  /** itemNames that name nothing -- dead fields, a defect list. */
  phantom: Record<string, string[]>;
  /** Declared parameters an interface reaches today, and must keep reaching. */
  reachable: Record<string, string[]>;
}

describe("task interface parameter coverage", () => {
  const gaps = currentGaps();
  const phantoms = currentPhantoms();
  const reached = currentlyReachable();

  if (UPDATING) {
    it("regenerates the baseline", () => {
      const next: Baseline = { gaps, phantom: phantoms, reachable: reached };
      writeFileSync(BASELINE, `${JSON.stringify(next, null, 1)}\n`);
      expect(existsSync(BASELINE)).toBe(true);
    });
    return;
  }

  const baseline: Baseline = JSON.parse(readFileSync(BASELINE, "utf8"));

  it("exposes no fewer parameters than the recorded baseline", () => {
    const regressions: string[] = [];
    for (const [task, missing] of Object.entries(gaps)) {
      const allowed = new Set(baseline.gaps[task] ?? []);
      const fresh = missing.filter((p) => !allowed.has(p));
      if (fresh.length) regressions.push(`${task}: ${fresh.join(", ")}`);
    }
    expect(
      regressions,
      "These parameters were reachable in the Qt GUI and are no longer reachable " +
        "here. Add them to the interface, or if the omission is deliberate, " +
        "regenerate with: UPDATE_COVERAGE_BASELINE=1 npx vitest run task-parameter-coverage"
    ).toEqual([]);
  });

  it("keeps reaching every parameter it reaches today", () => {
    const lost: string[] = [];
    for (const [task, was] of Object.entries(baseline.reachable)) {
      const now = new Set(reached[task] ?? []);
      const dropped = was.filter((p) => !now.has(p));
      if (dropped.length) lost.push(`${task}: ${dropped.join(", ")}`);
    }
    expect(
      lost,
      "These parameters used to be reachable in the form and no longer are. " +
        "Unlike the Qt gap list this covers everything the task declares, so " +
        "it is what catches a refactor quietly dropping a field. If the removal " +
        "is deliberate, regenerate with: UPDATE_COVERAGE_BASELINE=1 npx vitest " +
        "run task-parameter-coverage"
    ).toEqual([]);
  });

  it("has a baseline that still matches what is missing", () => {
    const stale: string[] = [];
    for (const [task, allowed] of Object.entries(baseline.gaps)) {
      const missing = new Set(gaps[task] ?? []);
      const closed = allowed.filter((p) => !missing.has(p));
      if (closed.length) stale.push(`${task}: ${closed.join(", ")}`);
    }
    for (const [task, allowed] of Object.entries(baseline.phantom)) {
      const live = new Set(phantoms[task] ?? []);
      const fixed = allowed.filter((n) => !live.has(n));
      if (fixed.length) stale.push(`${task} (phantom): ${fixed.join(", ")}`);
    }
    expect(
      stale,
      "Good news -- these gaps are closed. Lock the improvement in with: " +
        "UPDATE_COVERAGE_BASELINE=1 npx vitest run task-parameter-coverage"
    ).toEqual([]);
  });

  it("can read every interface's parameter names", () => {
    // Nothing is exempt today, and it should stay that way: an interface the
    // reader cannot parse leaves the ratchet silently, taking its parameters
    // with it. Two computed idioms are understood -- `itemName={key}` over a
    // config array of `{ key: "NAME" }`, and an indexed family written
    // ``itemName={`PREFIX${n}`}``. A third would need teaching here, and
    // that is the point of failing rather than skipping.
    const unreadable: string[] = [];
    for (const [task, module] of Object.entries(registry)) {
      if (exposedParameters(module).dynamic) unreadable.push(task);
    }
    expect(
      unreadable.sort(),
      "This interface computes itemName in a way the reader does not " +
        "understand, so its parameters go unmeasured. Either use a literal " +
        "name, or teach exposedParameters() the idiom."
    ).toEqual([]);
  });

  it("keeps every exclusion earning its place", () => {
    const stale: string[] = [];
    for (const [task, names] of Object.entries(excluded)) {
      const parameters = fixture.tasks[task];
      if (!parameters) {
        stale.push(`${task}: no such task in the fixture`);
        continue;
      }
      const sections = sectionOf(parameters);
      const module = registry[task];
      const exposure = module ? exposedParameters(module) : null;
      const ambiguous = ambiguousLeaves(parameters);

      for (const name of names) {
        if (!sections.has(name)) {
          stale.push(`${task}.${name}: no longer declared`);
        } else if (
          exposure &&
          !exposure.dynamic &&
          reachable(name, sections.get(name)!, exposure, ambiguous)
        ) {
          stale.push(`${task}.${name}: the interface reaches it now`);
        }
      }
    }
    expect(
      stale,
      "An exclusion has to keep describing something real. A parameter that is " +
        "no longer declared leaves a stale excuse behind a rename; one the " +
        "interface has since grown a field for means the decision was reversed " +
        "and the note now contradicts the code. Remove these from " +
        "coverage-exclusions.json."
    ).toEqual([]);
  });

  it("names only parameters the task actually declares", () => {
    const fresh: string[] = [];
    for (const [task, names] of Object.entries(phantoms)) {
      const allowed = new Set(baseline.phantom[task] ?? []);
      const added = names.filter((n) => !allowed.has(n));
      if (added.length) fresh.push(`${task}: ${added.join(", ")}`);
    }
    expect(
      fresh,
      "These itemName values match no declared parameter, so the field renders " +
        "as nothing at all. Usually a guiLabel used where the parameter name " +
        "belongs -- prosmart had itemName=\"Target\" for XYZIN. Fix the name, or " +
        "if the parameter is genuinely built at runtime, add the task to " +
        "PHIL_DRIVEN."
    ).toEqual([]);
  });

  it("gives every registered interface something to render", () => {
    const empty: string[] = [];
    for (const [task, module] of Object.entries(registry)) {
      const parameters = fixture.tasks[task];
      if (!parameters) continue;
      const declared = Object.values(parameters.declared).flat();
      if (declared.length === 0) continue;
      const exposure = exposedParameters(module);
      if (exposure.dynamic || exposure.names.size > 0 || exposure.autoRendered.size > 0) {
        continue;
      }
      empty.push(`${task} (${declared.length} declared parameters)`);
    }
    expect(
      empty,
      "A registered interface that names no parameter renders as an empty form. " +
        "Falling back to GenericInterface would serve a user better -- remove the " +
        "entry from TASK_INTERFACES, or build the interface out."
    ).toEqual([]);
  });
});
