# Generated by Django 5.2.9 on 2026-01-05 16:40

import compounds.assays.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('unassigned', 'Unassigned')], default='unassigned', max_length=20)),
                ('results', models.JSONField(default=dict, help_text='Fitted parameters: {EC50, Hill, minVal, maxVal, KPI, ...}')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
            },
        ),
        migrations.CreateModel(
            name='DilutionSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concentrations', models.JSONField(default=list, help_text='List of concentrations, e.g., [100, 30, 10, 3, 1, 0.3]')),
                ('unit', models.CharField(choices=[('nM', 'nanomolar'), ('uM', 'micromolar'), ('mM', 'millimolar')], default='nM', max_length=10)),
            ],
            options={
                'verbose_name': 'Dilution Series',
                'verbose_name_plural': 'Dilution Series',
            },
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_file', models.FileField(help_text='Raw data file (Excel, CSV, etc.)', upload_to=compounds.assays.models._assay_data_path)),
                ('labbook_number', models.IntegerField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, help_text="Target tested (may differ from compound's registered target)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assays', to='registry.target')),
            ],
            options={
                'verbose_name': 'Assay',
                'verbose_name_plural': 'Assays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compound_name', models.CharField(blank=True, help_text='Original name from data file (for matching)', max_length=256)),
                ('row', models.IntegerField()),
                ('start_column', models.IntegerField()),
                ('end_column', models.IntegerField()),
                ('extracted_data', models.JSONField(default=dict, help_text='Parsed data points from source file')),
                ('skip_points', models.JSONField(default=list, help_text='Indices of points to exclude from fitting')),
                ('svg_file', models.ImageField(blank=True, help_text='Fitted curve plot', null=True, upload_to=compounds.assays.models._series_svg_path)),
                ('analysis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_series', to='assays.analysisresult')),
                ('assay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_series', to='assays.assay')),
                ('compound', models.ForeignKey(blank=True, help_text='Linked compound (matched by name/barcode)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assay_results', to='registry.compound')),
                ('dilution_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assays.dilutionseries')),
            ],
            options={
                'verbose_name': 'Data Series',
                'verbose_name_plural': 'Data Series',
                'ordering': ['compound_name'],
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smiles', models.CharField(help_text='Proposed structure', max_length=1024)),
                ('rationale', models.TextField(help_text='Design rationale')),
                ('model_url', models.URLField(blank=True, help_text='Link to 3D model or docking pose')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('chemistry', 'In Chemistry'), ('shelved', 'Shelved'), ('made', 'Made')], default='pending', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('svg_file', models.ImageField(blank=True, null=True, upload_to=compounds.assays.models._hypothesis_svg_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent hypothesis this was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assays.hypothesis')),
                ('product_compound', models.ForeignKey(blank=True, help_text='Resulting compound if hypothesis was synthesized', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_hypotheses', to='registry.compound')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='registry.target')),
            ],
            options={
                'verbose_name': 'Hypothesis',
                'verbose_name_plural': 'Hypotheses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('analysis_method', models.CharField(choices=[('hill_langmuir', 'Hill-Langmuir'), ('hill_langmuir_fix_hill', 'Hill-Langmuir (fixed Hill coefficient)'), ('hill_langmuir_fix_hill_minmax', 'Hill-Langmuir (fixed Hill and min/max)'), ('hill_langmuir_fix_minmax', 'Hill-Langmuir (fixed min/max)'), ('ms_intact', 'MS-Intact'), ('table_of_values', 'Table of values')], default='hill_langmuir', max_length=50)),
                ('pherastar_table', models.CharField(blank=True, choices=[('none', 'None'), ('table_1', 'Table 1'), ('table_2', 'Table 2'), ('table_3', 'Table 3')], default='table_3', help_text='PHERAstar plate reader table selection', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('preferred_dilutions', models.ForeignKey(blank=True, help_text='Default dilution series for experiments using this protocol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assays.dilutionseries')),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocols',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assay',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assays', to='assays.protocol'),
        ),
        migrations.CreateModel(
            name='ProtocolDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=compounds.assays.models._protocol_doc_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assays.protocol')),
            ],
            options={
                'verbose_name': 'Protocol Document',
                'verbose_name_plural': 'Protocol Documents',
            },
        ),
    ]
