# Generated by Django 5.2.9 on 2026-01-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assay',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='compound_name',
            field=models.CharField(blank=True, help_text='Original name from data file (for matching)', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='model_url',
            field=models.CharField(blank=True, help_text='Link to 3D model or docking pose', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='rationale',
            field=models.TextField(blank=True, help_text='Design rationale', null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
