# Generated by Django 5.2.9 on 2026-01-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0002_alter_assay_comments_alter_dataseries_compound_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='pherastar_table',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('table_1', 'Table 1'), ('table_2', 'Table 2'), ('table_3', 'Table 3')], default='table_3', help_text='PHERAstar plate reader table selection', max_length=32, null=True),
        ),
    ]
