# Generated by Django migration
from django.db import migrations


class Migration(migrations.Migration):
    """Rename svg_file to plot_image on DataSeries model.

    The field stores fitted curve plot images which can be any image format
    (SVG, PNG, JPG, etc.), not just SVGs. The new name better reflects this.
    """

    dependencies = [
        ('assays', '0006_add_tight_binding_wang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataseries',
            old_name='svg_file',
            new_name='plot_image',
        ),
    ]
