# Generated by Django migration
from django.db import migrations, models
import compounds.assays.models


class Migration(migrations.Migration):
    """Increase max_length to 255 for ImageField/FileField to support longer paths.

    PostgreSQL enforces varchar limits (default 100 for Django FileField/ImageField),
    while SQLite does not. Legacy file paths with UUIDs can exceed 100 characters.
    """

    dependencies = [
        ('assays', '0011_protocol_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoldocument',
            name='file',
            field=models.FileField(
                max_length=255,
                upload_to=compounds.assays.models._protocol_doc_path
            ),
        ),
        migrations.AlterField(
            model_name='assay',
            name='data_file',
            field=models.FileField(
                help_text='Raw data file (Excel, CSV, etc.)',
                max_length=255,
                upload_to=compounds.assays.models._assay_data_path
            ),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='plot_image',
            field=models.ImageField(
                blank=True,
                help_text='Fitted curve plot image',
                max_length=255,
                null=True,
                upload_to=compounds.assays.models._series_plot_path
            ),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='svg_file',
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=compounds.assays.models._hypothesis_svg_path
            ),
        ),
    ]
