# Generated by Django migration for PlateLayout model
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Add PlateLayout model and update Protocol.plate_layout from JSONField to FK.

    This migration:
    1. Creates the PlateLayout model for reusable plate configurations
    2. Adds a temporary FK field (plate_layout_new) to Protocol
    3. Data migration to create PlateLayout records from existing JSON
    4. Removes the old JSONField
    5. Renames plate_layout_new to plate_layout
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assays', '0012_alter_file_field_max_lengths'),
    ]

    operations = [
        # Step 1: Create PlateLayout model
        migrations.CreateModel(
            name='PlateLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the plate layout', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this layout', null=True)),
                ('config', models.JSONField(default=dict, help_text='Plate layout configuration: control positions, sample region, replicate pattern')),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in layouts shipped with the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plate_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plate Layout',
                'verbose_name_plural': 'Plate Layouts',
                'ordering': ['name'],
            },
        ),
        # Step 2: Add temporary FK field to Protocol
        migrations.AddField(
            model_name='protocol',
            name='plate_layout_new',
            field=models.ForeignKey(blank=True, help_text='Plate layout template: control positions, sample region, replicate pattern', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols_new', to='assays.platelayout'),
        ),
        # Step 3: Data migration handled in separate migration (0014)
        # Step 4-5: JSONField removal and rename handled in separate migration (0015)
    ]
