# Generated by Django 5.2.9 on 2026-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assays', '0025_backfill_adme_import_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='poor_value',
            field=models.FloatField(blank=True, help_text="Value considered poor for this protocol's KPI (in the KPI's native units)", null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='target_value',
            field=models.FloatField(blank=True, help_text="Value considered excellent for this protocol's KPI (in the KPI's native units)", null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='threshold_scale',
            field=models.CharField(choices=[('log', 'Logarithmic'), ('linear', 'Linear')], default='log', help_text='Interpolation scale between target_value and poor_value (log for concentrations, linear for percentages)', max_length=10),
        ),
    ]
