from __future__ import print_function

"""
    lidiaAcedrg_gui.py
    Copyright (C) 2015 Newcastle University
    Author: Martin Noble
    
    """

from PySide2 import QtGui, QtWidgets,QtCore
import os
from qtgui.CCP4TaskWidget import CTaskWidget
import gemmi

#-------------------------------------------------------------------
class lidiaAcedrgNew_gui(CTaskWidget):
    #-------------------------------------------------------------------
    TASKMODULE = 'ligands'       # Where this plugin will appear on the gui
    TASKTITLE = 'Make Ligand - AceDRG'     # A short title for gui menu
    DESCRIPTION = 'Generate a PDB file and dictionary (acedrg) from MOL file, SMILES string/file, or sketch (lidia).<br>Optionally match atom names to known structures.'
    TASKVERSION = 0.1
    TASKNAME = 'LidiaAcedrgNew'
    RANK=1

    def drawContents(self):
        indent = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
        
        self.openFolder(folderFunction='inputData')
        
        self.createLine ( [ 'advice',' '] )
        self.createLine ( [ 'advice',' '] )
        
        self.createLine(['subtitle','Start point'])
        self.openSubFrame( frame=[True])
        self.createLine ( [ 'label','Start with molecular structure from ','stretch','widget','MOLSMILESORSKETCH' ] )
        
        self.createLine ( [ 'advice', 'Will launch Lidia to sketch molecule. Click Apply <b>and</b> Close in Lidia when sketch is ready.' ], toggle=['MOLSMILESORSKETCH','open',['SKETCH']])
        self.createLine ( [ 'advice', 'Optionally can provide a starting monomer for the Lidia sketch:' ], toggle=['MOLSMILESORSKETCH','open',['SKETCH']])
        
        self.createLine ( [ 'widget','MOLIN' ], toggle=['MOLSMILESORSKETCH','open',['SKETCH','MOL']] )
        self.createLine ( [ 'widget','MOL2IN' ], toggle=['MOLSMILESORSKETCH','open',['MOL2']] )
        
        self.createLine ( [ 'widget', '-guiMode', 'multiLine', 'SMILESIN' ] , toggle=['MOLSMILESORSKETCH','open',['SMILES']])
        self.createLine ( [ 'label', 'SMILES file', 'widget', 'SMILESFILEIN' ] , toggle=['MOLSMILESORSKETCH','open',['SMILESFILE']])
        self.createLine ( [ 'widget', 'DICTIN2' ] , toggle=['MOLSMILESORSKETCH','open',['DICT']])
        self.connectDataChanged('DICTIN2', self.updateTLC)
        self.createLine ( [ 'widget', 'USE_COORD', 'label', 'Use the coordinates from the input file' ],
                          toggle=['MOLSMILESORSKETCH','open',['MOL','MOL2','DICT']] )
        self.createLine ( [ 'widget', 'TOGGLE_METAL', 'label' , 'This monomer contains a metal atom.' ] )
        self.connectDataChanged('controlParameters.TOGGLE_METAL', self.ToggleShowContainsMetal)
        self.createLine ( [ 'label', indent + 'Provide a relevant structure model in complex with this monomer to get ideal bond angles in the output:'] , toggleFunction=[self.ToggleShowContainsMetal, ['controlParameters.TOGGLE_METAL']])
        self.createLine ( [ 'label', indent, 'widget', 'METAL_STRUCTURE'] , toggleFunction=[self.ToggleShowContainsMetal, ['controlParameters.TOGGLE_METAL']])
        self.closeSubFrame()


        self.createLine(['subtitle', 'Output monomer'])
        self.openSubFrame( frame=[True])
        self.createLine ( [ 'label', 'Monomer code (3-5 characters)','stretch','widget','TLC' ])
        # Codes XXX, LIG, DRG, INH, LG0, LG1, LG2, LG3, LG4, LG5, LG6, LG7, LG8, LG9 are reserved by Coot and cannot be used here.
        self.createLine ( [ 'widget', 'NOPROT', 'label' , 'No further protonation/deprotonation to be done by AceDRG' ] )
        self.closeSubFrame()
        
        try:
            import ccp4srs
            dummy = ccp4srs.Graph()
            self.createLine(['subtitle','Atom Naming'])
            self.openSubFrame( frame=[True])
            self.createLine ( [ 'label','Attempt to match atom names with ','stretch','widget','ATOMMATCHOPTION' ] )
            self.createLine ( [ 'label','Three letter code to match atom names with','stretch','widget','MATCHTLC' ], toggle=['ATOMMATCHOPTION','open',['MONLIBCODE']])
            self.createLine ( [ 'label','User supplied dictionary to match atom names with','stretch' ], toggle=['ATOMMATCHOPTION','open',['LOCALDICT']])
            self.createLine ( [ 'widget','DICTIN' ], toggle=['ATOMMATCHOPTION','open',['LOCALDICT']])
            self.closeSubFrame()
        except:
            print("Atom naming requires more recent version of ccp4srs-python")

        #self.openFolder(title='Advanced')
        self.createLine(['subtitle','Advanced'], toggle=['MOLSMILESORSKETCH','open',['SMILES', 'SMILESFILE', 'SKETCH']])
        self.openSubFrame( frame=[True] , toggle=['MOLSMILESORSKETCH','open',['SMILES', 'SMILESFILE', 'SKETCH']])
        """
        self.createLine(['advice','Geometry restraints *always* taken from ACEDRG'])
        self.createLine(['label','Output conformers generated by','stretch','widget','CONFORMERSFROM'])
        self.openSubFrame( frame=[False], toggle=['CONFORMERSFROM','open',['RDKIT']] )
        """
        self.createLine ( [ 'label','Number of random RDKit start structures','widget','NRANDOM' ] )# , toggle=['MOLSMILESORSKETCH','open',['SMILES', 'SMILESFILE']])
        self.closeSubFrame()


    def isValid(self):
        invalidElements = super(lidiaAcedrgNew_gui, self).isValid()
        if self.container.inputData.MOLSMILESORSKETCH.__str__() == 'SMILES':
            self.container.inputData.MOLIN.unSet()
        return invalidElements


    def updateTLC(self):
        tlc = None
        try:
            blocks = gemmi.cif.read(str(self.container.inputData.DICTIN2.fullPath))
            for block in blocks:
                tlc = block.find_value('_chem_comp.three_letter_code')
                if tlc:
                    break
                tlc = block.find_value('_chem_comp.id')
                if tlc:
                    break
            if tlc:
                if len(str(tlc)) >= 3 and len(str(tlc)) <= 5:
                    self.container.inputData.TLC.set(str(tlc))
            self.ToggleShowContainsMetal(fromUpdateTLC=True)
        except:
            pass

    def ToggleShowContainsMetal(self, fromUpdateTLC=False):
        if self.container.controlParameters.TOGGLE_METAL and not fromUpdateTLC:
            return True
        if not self.container.controlParameters.TOGGLE_METAL and not fromUpdateTLC:
            return False
        if self.container.inputData.MOLSMILESORSKETCH != 'DICT':
            return False
        if not str(self.container.inputData.DICTIN2.fullPath):
            return False
        if not os.path.isfile(str(self.container.inputData.DICTIN2.fullPath)):
            return False
        try:
            blocks = gemmi.cif.read(str(self.container.inputData.DICTIN2.fullPath))
            for block in blocks:
                for element in block.find_loop("_chem_comp_atom.type_symbol"):
                    if gemmi.Element(element).is_metal:
                        self.container.controlParameters.TOGGLE_METAL.set(True)
                        return True
        except:
            return False
