# Generated by Django 4.2.17 on 2024-12-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ccp4x", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobValueKeys",
            new_name="JobValueKey",
        ),
    ]
