# Generated by Django 4.2.17 on 2025-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4x', '0004_alter_projecttag_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='directory',
            field=models.IntegerField(choices=[(1, 'Job'), (2, 'Import')]),
        ),
        migrations.AlterField(
            model_name='fileuse',
            name='role',
            field=models.IntegerField(choices=[(0, 'OUT'), (1, 'IN')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Pending'), (2, 'Queued'), (3, 'Running'), (4, 'Interrupted'), (5, 'Failed'), (6, 'Finished'), (7, 'Running remotely'), (8, 'File holder'), (9, 'To delete'), (10, 'Unsatisfactory')], default=0),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='projects',
            field=models.ManyToManyField(related_name='tags', to='ccp4x.project'),
        ),
    ]
