# Generated by Django 4.2.18 on 2025-03-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4x', '0006_alter_jobcharvalue_job_alter_jobfloatvalue_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fileuse',
            unique_together={('file', 'job', 'role', 'job_param_name')},
        ),
    ]
