# Generated by Django 4.2.17 on 2025-09-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4x', '0007_alter_fileuse_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('general_set', 'General set'), ('fragment_set', 'Fragment set')], default='general_set', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('parent', 'Parent'), ('member', 'Member')], max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ccp4x.projectgroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='ccp4x.project')),
            ],
            options={
                'unique_together': {('group', 'project')},
            },
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='projects',
            field=models.ManyToManyField(related_name='groups', through='ccp4x.ProjectGroupMembership', to='ccp4x.project'),
        ),
    ]
