# Generated by Django 5.2.8 on 2025-11-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4x', '0009_alter_projecttag_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='projects',
            field=models.ManyToManyField(related_name='groups', through='ccp4x.ProjectGroupMembership', through_fields=('group', 'project'), to='ccp4x.project'),
        ),
    ]
