import glob
import os
import pathlib
import shutil
import xml.etree.ElementTree as ET

import coot_headless_api

from ccp4i2.core.CCP4ModelData import CPdbDataFile
from ccp4i2.core.CCP4PluginScript import CPluginScript


class coot_find_ligand(CPluginScript):
    TASKTITLE = "Find ligand with Coot API"
    TASKNAME = "coot_find_ligand"
    WHATNEXT = ["prosmart_refmac"]

    def startProcess(self):
        inputData = self.container.inputData
        outputData = self.container.outputData
        params = self.container.controlParameters

        if inputData.XYZIN.isMMCIF():
            path = pathlib.Path(str(outputData.XYZOUT.fullPath))
            outputData.XYZOUT.setFullPath(str(path.with_suffix(".cif")))
            outputData.XYZOUT.contentFlag.set(CPdbDataFile.CONTENT_FLAG_MMCIF)

        xyzin = str(inputData.XYZIN.fullPath)
        mtzin = str(inputData.FPHI.fullPath)
        cifin = str(inputData.DICT.fullPath)
        xyzout = str(outputData.XYZOUT.fullPath)

        # Change to job directory so coot's intermediate files are created there
        # (coot_headless_api writes map files to CWD during fit_ligand)
        original_cwd = os.getcwd()
        job_dir = os.path.dirname(xyzout)
        if job_dir:
            os.chdir(job_dir)

        try:
            mc = coot_headless_api.molecules_container_py(True)
            mc.set_make_backups(False)
            mc.set_use_gemmi(False)
            imol = mc.read_pdb(xyzin)
            imap = mc.read_mtz(mtzin, "F", "PHI", "", False, False)
            mc.import_cif_dictionary(cifin, mc.get_imol_enc_any())
            ilig = mc.get_monomer(str(inputData.COMPID))

            result = mc.fit_ligand(
                imol_protein=imol,
                imol_map=imap,
                imol_ligand=ilig,
                n_rmsd=float(params.THRESHOLD),
                use_conformers=bool(params.FLEXIBLE),
                n_conformers=int(params.CONFORMERS),
            )

            xmlRoot = ET.Element("coot_find_ligand")
            clusterMols = {}
            for info in result:
                if info.cluster_idx not in clusterMols:
                    clusterMols[info.cluster_idx] = str(info.imol)
                    element = ET.SubElement(xmlRoot, "AddedLigand")
                    element.set("clusterVolume", str(info.get_cluster_volume()))
                    element.set("fittingScore", str(info.get_fitting_score()))
            mc.merge_molecules(imol, ":".join(clusterMols.values()))
            mc.write_coordinates(imol, xyzout)

            ET.ElementTree(xmlRoot).write(self.makeFileName("PROGRAMXML"))

            # Clean up coot intermediate files
            shutil.rmtree("coot-backup", ignore_errors=True)
            # Remove map files generated by fit_ligand() in CWD
            for pattern in ["molecules-container-fit-ligand-*.map", "wlig.output_map.map"]:
                for mapfile in glob.glob(pattern):
                    try:
                        os.remove(mapfile)
                    except OSError:
                        pass

            status = CPluginScript.FAILED
            if os.path.exists(xyzout):
                status = CPluginScript.SUCCEEDED
            self.reportStatus(status)
            return status

        finally:
            # Ensure we restore working directory even on error
            if job_dir:
                try:
                    os.chdir(original_cwd)
                except Exception:
                    pass
