# Generated by Django 5.2.9 on 2026-01-05 16:40

import compounds.registry.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.IntegerField(help_text='Auto-assigned within compound')),
                ('supplier_ref', models.CharField(blank=True, max_length=255)),
                ('labbook_number', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=4, help_text='Amount in mg', max_digits=10, null=True)),
                ('salt_code', models.CharField(blank=True, max_length=128)),
                ('molecular_weight', models.FloatField(blank=True, help_text='MW including salt (if different from parent)', null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['compound', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('initials', models.CharField(blank=True, help_text="Short code used in barcodes, e.g., 'NCL', 'AST'", max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BatchQCFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=compounds.registry.models._batch_qc_path)),
                ('comments', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_files', to='registry.batch')),
            ],
            options={
                'verbose_name': 'Batch QC File',
                'verbose_name_plural': 'Batch QC Files',
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_number', models.IntegerField(default=compounds.registry.models._next_reg_number, editable=False, help_text='Auto-assigned registration number', unique=True)),
                ('smiles', models.TextField(help_text='SMILES structure notation')),
                ('rdkit_smiles', models.TextField(blank=True, help_text='RDKit canonical SMILES (for duplicate detection)')),
                ('inchi', models.TextField(blank=True, help_text='InChI structure identifier')),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('stereo_comment', models.CharField(choices=[('unset', 'Unset'), ('achiral', 'Achiral'), ('racemic', 'Racemic mixture'), ('single_unknown', 'Single enantiomer, configuration unknown'), ('r_enantiomer', 'R enantiomer'), ('s_enantiomer', 'S enantiomer'), ('non_racemic_mixture', 'Non-racemic stereoisomer mixture'), ('four_diastereomers', 'Mixture of 4 diastereoisomers'), ('two_diastereomers', 'Mixture of 2 diastereoisomers'), ('single_diastereomer_unknown', 'Single diastereoisomer, configuration unknown'), ('rr_diastereomer', 'RR diastereoisomer'), ('rs_diastereomer', 'RS diastereoisomer'), ('sr_diastereomer', 'SR diastereoisomer'), ('ss_diastereomer', 'SS diastereoisomer'), ('epimer_mixture', 'Mixture of epimers'), ('ez_mixture', 'Mixture of E and Z isomers'), ('e_isomer', 'E isomer'), ('z_isomer', 'Z isomer')], default='unset', max_length=70)),
                ('supplier_ref', models.CharField(blank=True, help_text="Supplier's catalog or reference number", max_length=255)),
                ('labbook_number', models.IntegerField(help_text='Lab notebook number')),
                ('page_number', models.IntegerField(help_text='Page number in lab notebook')),
                ('compound_number', models.IntegerField(default=1, help_text='Compound number on page (if multiple)')),
                ('legacy_registered_by', models.CharField(blank=True, help_text='Original user_name from legacy system (for historical records)', max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('svg_file', models.ImageField(blank=True, help_text='SVG structure image', null=True, upload_to=compounds.registry.models._compound_svg_path)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_compounds', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compounds', to='registry.supplier')),
            ],
            options={
                'verbose_name': 'Compound',
                'verbose_name_plural': 'Compounds',
                'ordering': ['-reg_number'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='registry.compound'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.supplier'),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent target for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='registry.target')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompoundTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('mol2d', models.TextField(help_text='2D MOL block for the template structure')),
                ('svg_file', models.ImageField(blank=True, null=True, upload_to=compounds.registry.models._template_svg_path)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='registry.target')),
            ],
            options={
                'verbose_name': 'Compound Template',
                'verbose_name_plural': 'Compound Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='compound',
            name='target',
            field=models.ForeignKey(help_text='Drug discovery target this compound was designed for', on_delete=django.db.models.deletion.PROTECT, related_name='compounds', to='registry.target'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('compound', 'batch_number')},
        ),
    ]
