# Generated by Django 5.2.9 on 2026-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='initials',
            field=models.CharField(blank=True, help_text="Short code used in barcodes, e.g., 'NCL', 'AST'", max_length=16, null=True, unique=True),
        ),
    ]
