# Generated by Django 5.2.9 on 2026-01-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_supplier_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='labbook_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='salt_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supplier_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchqcfile',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.TextField(blank=True, help_text='InChI structure identifier', null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='labbook_number',
            field=models.IntegerField(blank=True, help_text='Lab notebook number', null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='legacy_registered_by',
            field=models.CharField(blank=True, help_text='Original user_name from legacy system (for historical records)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='page_number',
            field=models.IntegerField(blank=True, help_text='Page number in lab notebook', null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='rdkit_smiles',
            field=models.TextField(blank=True, help_text='RDKit canonical SMILES (for duplicate detection)', null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='supplier_ref',
            field=models.CharField(blank=True, help_text="Supplier's catalog or reference number", max_length=255, null=True),
        ),
    ]
