# Generated by Django 5.2.9 on 2026-01-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_batch_comments_alter_batch_labbook_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
    ]
