# Generated by Django 5.2.9 on 2026-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_batch_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchqcfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
