# Generated by Django 5.2.9 on 2026-01-14

from django.db import migrations, models
import compounds.registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_batchqcfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchqcfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=compounds.registry.models._batch_qc_path),
        ),
    ]
