# Generated by Django migration
from django.db import migrations, models
import compounds.registry.models


class Migration(migrations.Migration):
    """Increase max_length to 255 for ImageField/FileField to support longer paths.

    PostgreSQL enforces varchar limits (default 100 for Django FileField/ImageField),
    while SQLite does not. Legacy file paths with UUIDs can exceed 100 characters.
    """

    dependencies = [
        ('registry', '0010_target_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Branding image for the target dashboard',
                max_length=255,
                null=True,
                upload_to=compounds.registry.models._target_image_path
            ),
        ),
        migrations.AlterField(
            model_name='compound',
            name='svg_file',
            field=models.ImageField(
                blank=True,
                help_text='SVG structure image',
                max_length=255,
                null=True,
                upload_to=compounds.registry.models._compound_svg_path
            ),
        ),
        migrations.AlterField(
            model_name='compoundtemplate',
            name='svg_file',
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=compounds.registry.models._template_svg_path
            ),
        ),
    ]
