# Generated by hand
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add saved_aggregation_view JSONField to Target model.

    Allows storing an aggregation query configuration per target,
    which is displayed on the target dashboard page.
    """

    dependencies = [
        ('registry', '0011_alter_file_field_max_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='saved_aggregation_view',
            field=models.JSONField(
                blank=True,
                null=True,
                help_text='Saved aggregation query configuration for dashboard display. '
                          'Schema: {protocol_names: string[], compound_search: string, '
                          "output_format: 'compact'|'medium'|'long', "
                          "aggregations: ('geomean'|'count'|'stdev'|'list')[], "
                          "status: 'valid'|'invalid'|'unassigned'|''}"
            ),
        ),
    ]
