# Generated by Django 5.2.9 on 2026-04-21 09:48

import compounds.registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_migrate_labbook_to_notebook_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchqcfile',
            name='kind',
            field=models.CharField(choices=[('lcms', 'LC-MS'), ('hrms', 'HR-MS'), ('nmr', 'NMR'), ('hplc', 'HPLC'), ('other', 'Other')], default='other', help_text='Type of QC document', max_length=16),
        ),
        migrations.AddField(
            model_name='batchqcfile',
            name='label',
            field=models.CharField(blank=True, help_text="Display text, e.g., 'LCMS-001'", max_length=255),
        ),
        migrations.AddField(
            model_name='batchqcfile',
            name='url',
            field=models.URLField(blank=True, help_text='External URL to QC document (SharePoint, ELN, cloud storage)', max_length=2048),
        ),
        migrations.AlterField(
            model_name='batchqcfile',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded QC file', max_length=255, upload_to=compounds.registry.models._batch_qc_path),
        ),
        migrations.AlterField(
            model_name='target',
            name='saved_aggregation_view',
            field=models.JSONField(blank=True, help_text="Saved aggregation query configuration for dashboard display. Schema: {protocol_names: string[], compound_search: string, output_format: 'compact'|'medium'|'long'|'pivot'|'cards', aggregations: ('geomean'|'count'|'stdev'|'list')[], status: 'valid'|'invalid'|'unassigned'|'', concentration_display?: 'natural'|'nM'|'uM'|'mM'|'pConc', include_properties?: string[]}", null=True),
        ),
    ]
