# Generated by Django 5.2.9 on 2026-04-22 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_extend_batchqcfile_url_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text="HGNC-approved gene symbol, e.g. 'EGFR', 'SKP2'.", max_length=32, unique=True)),
                ('hgnc_id', models.CharField(blank=True, db_index=True, help_text="HGNC stable ID, e.g. 'HGNC:3236'.", max_length=32)),
                ('name', models.CharField(blank=True, help_text="Full gene name from HGNC, e.g. 'epidermal growth factor receptor'.", max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Union of HGNC alias_symbol and prev_symbol lists.')),
                ('uniprot_ids', models.JSONField(blank=True, default=list, help_text='UniProt accession(s); typically one primary + isoforms.')),
                ('ensembl_gene_id', models.CharField(blank=True, db_index=True, help_text="Ensembl gene ID, e.g. 'ENSG00000146648'.", max_length=32)),
                ('hydration_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('partial', 'Partial'), ('failed', 'Failed'), ('manual', 'Manual override')], default='pending', help_text='State of HGNC hydration for this gene.', max_length=16)),
                ('hydrated_at', models.DateTimeField(blank=True, help_text='Last successful hydration timestamp.', null=True)),
                ('hydration_source', models.CharField(blank=True, help_text="'hgnc-api', 'hgnc-snapshot', 'manual', etc.", max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gene',
                'verbose_name_plural': 'Genes',
                'ordering': ['symbol'],
            },
        ),
        migrations.AddField(
            model_name='target',
            name='genes',
            field=models.ManyToManyField(blank=True, help_text='Biological gene(s) underlying this target. Multi-gene for PPI / complex / pathway targets.', related_name='targets', to='registry.gene'),
        ),
    ]
