# Generated by Django 5.2.9 on 2026-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_gene_target_genes'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='scorecard_config',
            field=models.JSONField(blank=True, help_text="Per-target scorecard definition for spider / radar visualisation. Schema: {axes: ScorecardAxis[]} where each axis is {label: string, kind: 'protocol'|'ratio'|'worst_of'|'lipinski', target_value?: number, poor_value?: number, threshold_scale?: 'log'|'linear', protocol_id?: uuid (kind='protocol'), numerator_id?: uuid, denominator_id?: uuid (kind='ratio'), protocol_ids?: uuid[] (kind='worst_of')}. kind='lipinski' takes no extra fields; score is 0-4.", null=True),
        ),
    ]
