# Generated by Django 5.2.9 on 2026-04-27 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_add_target_scorecard_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaffoldExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Canonical name chemists will type ("indazole", "Series 1")', max_length=64)),
                ('smarts', models.CharField(help_text='SMARTS pattern; matched via RDKit HasSubstructMatch', max_length=512)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Additional typed forms that map to this entry (e.g. plurals, abbreviations)')),
                ('notes', models.TextField(blank=True, help_text='Human gloss explaining what the fragment captures (e.g. "Series 1: 5-6 fused heterocycles, atoms 2/4 may be C or N")')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_prompt', models.TextField(blank=True, help_text='Original NLP prompt that triggered the addition, if any')),
                ('llm_generated', models.BooleanField(default=False, help_text='True when the SMARTS was proposed by the LLM (slice 18+); False when typed by the chemist directly.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scaffold_extensions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, help_text='If set, this entry only resolves under that target/project. Null = shared across all projects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scaffold_extensions', to='registry.target')),
            ],
            options={
                'verbose_name': 'Scaffold extension',
                'verbose_name_plural': 'Scaffold extensions',
                'ordering': ['target__name', 'name'],
                'unique_together': {('name', 'target')},
            },
        ),
    ]
