# Generated by Django 5.2.9 on 2026-04-27 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_scaffoldextension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Display name (typically the NLP scope sentence). Shown in the aggregation header.', max_length=256)),
                ('compound_ids', models.JSONField(default=list, help_text='List of compound formatted_ids (e.g. ["NCL-00026007", ...]). Same shape as the ?compound= URL param.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this selection becomes unreachable. Null = never expires (saved). Cleanup command deletes expired rows.', null=True)),
                ('source_prompt', models.TextField(blank=True, help_text='Original NLP prompt that created this selection, if any.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Selection',
                'verbose_name_plural': 'Selections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='registry_se_expires_6475ad_idx'), models.Index(fields=['created_by', '-created_at'], name='registry_se_created_32ace2_idx')],
            },
        ),
    ]
