# Generated by Django 5.2.9 on 2026-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecularproperties',
            name='morgan_fp',
            field=models.TextField(blank=True, help_text='Morgan/ECFP4 fingerprint, radius 2, 2048 bits, "0101..." bit string.', null=True),
        ),
    ]
