# Generated by Django 5.2.9 on 2026-04-27 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0026_molecularproperties_morgan_fp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='is_saved',
            field=models.BooleanField(default=False, help_text="Saved selections never expire and appear in the chemist's persistent list."),
        ),
        migrations.AddField(
            model_name='selection',
            name='target',
            field=models.ForeignKey(blank=True, help_text='Optional project context. Used as a visibility hint for team-shared sessions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='registry.target'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this selection becomes unreachable. Null = saved (never expires). Cleanup command deletes expired rows.', null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='name',
            field=models.CharField(blank=True, help_text='Display name (typically the NLP scope sentence; renamable on save). Shown in the aggregation header.', max_length=256),
        ),
        migrations.AddIndex(
            model_name='selection',
            index=models.Index(fields=['created_by', 'is_saved'], name='registry_se_created_657aec_idx'),
        ),
    ]
