"""
Report fixture tests — standalone, no database or project zips required.

Each fixture directory contains:
  - program.xml        — raw program output XML
  - job_info.json      — jobInfo dict (with _fixture_meta)
  - expected_report.xml — normalised expected report output

Tests load these fixtures, instantiate the report class directly, and
compare the generated XML against the expected output. This validates
that the report layer produces stable output without needing 661MB of
test project zips or a database.

Fixtures are generated by extract_report_fixtures.py.

Usage:
    ./run_test.sh ccp4i2/tests/lib/test_report_fixtures.py
    ./run_test.sh ccp4i2/tests/lib/test_report_fixtures.py -k refmac

    # Re-baseline expected output for standalone mode (one-time after extraction):
    ./run_test.sh ccp4i2/tests/lib/test_report_fixtures.py --rebaseline
"""

from __future__ import annotations

import importlib
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

import pytest

# Resolve paths
_THIS_FILE = Path(__file__).resolve()
_FIXTURES_DIR = _THIS_FILE.parent / "report_fixtures"

# Pattern matching Python object repr addresses like "at 0x11c151a80"
_OBJ_ADDR_RE = re.compile(r" at 0x[0-9a-fA-F]+")


# --- Normalisation (must match extract_report_fixtures.py exactly) ---


def _normalise_xml(xml_element: ET.Element) -> str:
    """Normalise XML for stable comparison.

    Strips volatile attributes and scrubs non-deterministic content,
    then pretty-prints for readable diffs.
    """
    _strip_volatile_attrs(xml_element)
    _scrub_volatile_text(xml_element)
    _indent(xml_element)
    return ET.tostring(xml_element, encoding="unicode")


def _strip_volatile_attrs(element: ET.Element) -> None:
    for attr in ["key"]:
        if attr in element.attrib:
            del element.attrib[attr]
    for child in element:
        _strip_volatile_attrs(child)


def _scrub_volatile_text(element: ET.Element) -> None:
    for attr_name in list(element.attrib):
        val = element.get(attr_name)
        val = _OBJ_ADDR_RE.sub(" at 0xADDR", val)
        element.set(attr_name, val)
    if element.text:
        element.text = _OBJ_ADDR_RE.sub(" at 0xADDR", element.text)
    if element.tail:
        element.tail = _OBJ_ADDR_RE.sub(" at 0xADDR", element.tail)
    for child in element:
        _scrub_volatile_text(child)


def _indent(elem: ET.Element, level: int = 0) -> None:
    indent = "\n" + "  " * level
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = indent + "  "
        if not elem.tail or not elem.tail.strip():
            elem.tail = indent
        for child in elem:
            _indent(child, level + 1)
        if not child.tail or not child.tail.strip():
            child.tail = indent
    else:
        if level and (not elem.tail or not elem.tail.strip()):
            elem.tail = indent


# --- Fixture discovery ---


def _discover_fixtures() -> list[tuple[str, Path]]:
    """Discover all fixture directories, returning (name, path) pairs."""
    if not _FIXTURES_DIR.exists():
        return []
    fixtures = []
    for fixture_dir in sorted(_FIXTURES_DIR.iterdir()):
        if not fixture_dir.is_dir():
            continue
        # Must have all three files
        if all(
            (fixture_dir / f).exists()
            for f in ["program.xml", "job_info.json", "expected_report.xml"]
        ):
            fixtures.append((fixture_dir.name, fixture_dir))
    return fixtures


def _load_report_class(meta: dict[str, Any]) -> type | None:
    """Import and return the report class from fixture metadata."""
    module_name = meta["report_module"]
    class_name = meta["report_class"]
    try:
        module = importlib.import_module(module_name)
        return getattr(module, class_name)
    except (ImportError, AttributeError) as e:
        return None


def _unscrub_job_info(job_info: dict[str, Any], fixture_dir: Path) -> dict[str, Any]:
    """Replace <PROJECTS_DIR> placeholders with the fixture directory.

    Report classes may reference fileroot paths. We point them at the
    fixture directory so any relative path lookups won't crash, even
    though the actual data files aren't present.
    """
    placeholder = "<PROJECTS_DIR>"
    # Use the fixture dir's parent as a stand-in for projects dir
    fake_projects_dir = str(fixture_dir)

    def _unscrub(obj: Any) -> Any:
        if isinstance(obj, str):
            return obj.replace(placeholder, fake_projects_dir)
        elif isinstance(obj, dict):
            return {k: _unscrub(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [_unscrub(item) for item in obj]
        return obj

    return _unscrub(job_info)


# --- Test parametrization ---

_FIXTURES = _discover_fixtures()


@pytest.mark.skipif(not _FIXTURES, reason="No report fixtures found")
@pytest.mark.parametrize(
    "fixture_name,fixture_dir",
    _FIXTURES,
    ids=[f[0] for f in _FIXTURES],
)
def test_report_fixture(fixture_name: str, fixture_dir: Path, request: pytest.FixtureRequest) -> None:
    """Test that a report class produces the expected XML from fixture data."""
    rebaseline = request.config.getoption("--rebaseline", default=False)

    # Load fixture files
    job_info = json.loads((fixture_dir / "job_info.json").read_text(encoding="utf-8"))
    expected_xml = (fixture_dir / "expected_report.xml").read_text(encoding="utf-8")
    meta = job_info.pop("_fixture_meta")

    # Load report class
    report_class = _load_report_class(meta)
    if report_class is None:
        pytest.skip(f"Cannot import report class: {meta['report_module']}.{meta['report_class']}")

    # Parse program.xml
    program_xml_text = (fixture_dir / "program.xml").read_text(encoding="utf-8")
    if meta.get("has_program_xml", True) and program_xml_text != "<empty/>":
        try:
            output_xml = ET.fromstring(program_xml_text)
        except ET.ParseError:
            pytest.skip(f"Cannot parse program.xml for {fixture_name}")
    else:
        output_xml = None

    # Unscrub jobInfo paths (point at fixture dir as a harmless stand-in)
    job_info = _unscrub_job_info(job_info, fixture_dir)

    # Determine standardise flag
    non_standardise_statuses = ["Running", "Running remotely", "Pending", "Unknown", "Queued"]
    standardise = meta["job_status"] not in non_standardise_statuses

    # Instantiate report
    try:
        report = report_class(
            xmlnode=output_xml,
            jobInfo=job_info,
            standardise=standardise,
            jobStatus=meta["job_status"],
            jobNumber=meta["job_number"],
            xrtnode=None,
            projectId=job_info.get("projectid", ""),
        )
        report_etree = report.as_data_etree()
    except (FileNotFoundError, OSError, TypeError, AttributeError,
            KeyError, ValueError, RuntimeError, SyntaxError) as e:
        # Some report classes need disk files, database access, or specific
        # jobInfo keys that aren't available in standalone mode.
        pytest.skip(f"Report cannot run standalone: {e}")
    except Exception as e:
        pytest.fail(f"Report generation raised: {e}")

    # Normalise and compare
    actual_xml = _normalise_xml(report_etree)

    if actual_xml != expected_xml:
        if rebaseline:
            # Update expected output to match standalone mode
            (fixture_dir / "expected_report.xml").write_text(actual_xml, encoding="utf-8")
            # Clean up any stale actual file
            actual_path = fixture_dir / "actual_report.xml"
            if actual_path.exists():
                actual_path.unlink()
            pytest.skip(f"Re-baselined expected_report.xml for {fixture_name}")
        else:
            # Save actual for diffing
            actual_path = fixture_dir / "actual_report.xml"
            actual_path.write_text(actual_xml, encoding="utf-8")
            # Show first difference for quick debugging
            actual_lines = actual_xml.splitlines()
            expected_lines = expected_xml.splitlines()
            for i, (a, e) in enumerate(zip(actual_lines, expected_lines)):
                if a != e:
                    pytest.fail(
                        f"Report XML differs at line {i+1}:\n"
                        f"  expected: {e[:120]}\n"
                        f"  actual:   {a[:120]}\n"
                        f"  Full diff: diff {fixture_dir}/expected_report.xml {actual_path}"
                    )
            # Length difference
            pytest.fail(
                f"Report XML length differs: expected {len(expected_lines)} lines, "
                f"got {len(actual_lines)} lines\n"
                f"  Full diff: diff {fixture_dir}/expected_report.xml {actual_path}"
            )
