/**
 * Interactive tasks: those whose "program" is a window in the app rather
 * than a child process (the recorded Moorhen session). The server's task
 * registry flags them, `task_lookup/` exposes the flag, and Run on such a
 * job opens a session instead of dispatching; the client's job is to open
 * the session window. See docs/moorhen-task-design.md.
 */
import { useCallback } from "react";
import { useApi } from "../api";

export interface TaskLookupInfo {
  TASKTITLE?: string;
  DESCRIPTION?: string;
  shortTitle?: string;
  isAutogenerated?: boolean;
  supersededBy?: string | null;
  interactive?: boolean;
}
export type TaskLookup = Record<string, TaskLookupInfo>;

export function useTaskLookup(): TaskLookup | undefined {
  const api = useApi();
  const { data } = api.get<TaskLookup>("task_lookup/");
  return data;
}

/** `isInteractive(taskName)` from the server's registry; false until the
 *  lookup has loaded, so a caller never opens a window on a guess. */
export function useIsInteractiveTask(): (taskName?: string | null) => boolean {
  const lookup = useTaskLookup();
  return useCallback(
    (taskName?: string | null) => !!(taskName && lookup?.[taskName]?.interactive),
    [lookup],
  );
}

/** The session route: the URL is the whole job-specifying part of a launch. */
export const sessionRoute = (jobId: number) => `/ccp4i2/moorhen-page/session/${jobId}`;

/** Open the session window the way every Moorhen page is opened: a new
 *  window, which Electron turns into its own BrowserWindow. */
export function openSessionWindow(jobId: number) {
  window.open(sessionRoute(jobId), "_blank", "noopener,noreferrer");
}
