// Starting points for scripted Coot: the scripts the Qt interface put in
// the script box when a starting point was chosen
// (wrappers/coot_script_lines/script/coot_script_lines_gui.py on main).
// The menu was ported without them, so choosing one did nothing.
export const COOT_SCRIPT_TEMPLATES: Record<string, string> = {
  BLANK: "# Input molecules are given internal identifiers \"MolHandle_1\" etc\n# Input maps are given internal identifiers \"MapHandle_1\" etc\n# Input difference maps are given internal identifiers \"DifmapHandle_1\" etc\n#\n# The appropriate place to put output pdb files to be picked up by the system\n# is stored in the variable dropDir (see below for how to use this)\n#\n# Beware spaces...this is python after all\n#\n# Example commands you may wish to try can be explored by uncommenting the lines below\n# fill_partial_residues(MolHandle_1)\n# fit_protein(MolHandle_1)\n# stepped_refine_protein_for_rama(MolHandle_1)\n#\n# Per chain operations might look something like:\n# chainAMol = new_molecule_by_atom_selection(MolHandle_1,'//A')\n# otherChains = ['B','C','D','E','F','G','H','I','J','K','L']\n# for otherChain in otherChains:\n#    molToMove = new_molecule_by_atom_selection(MolHandle_1,'//A')\n#    newMolHandle = superpose_with_chain_selection(MolHandle_1, molToMove, otherChain, 'A', 1, 1, 1)\n#    merge_molecules(newMolHandle, molToMove)\n#\n# The following line ensures the output gets written out:\nwrite_pdb_file(MolHandle_1,os.path.join(dropDir,\"output.pdb\"))\n",
  FILL_PARTIAL_RESIDUES: "# Input molecules are given internal identifiers \"MolHandle_1\" etc\n# Input maps are given internal identifiers \"MapHandle_1\" etc\n# Input difference maps are given internal identifiers \"DifmapHandle_1\" etc\n#\n# The appropriate place to put output pdb files to be picked up by the system\n# is stored in the variable dropDir (see below for how to use this)\n#\n# Beware spaces...this is python after all\nfill_partial_residues(MolHandle_1)\nwrite_pdb_file(MolHandle_1,os.path.join(dropDir,\"output.pdb\"))\n",
  FIT_PROTEIN: "# Input molecules are given internal identifiers \"MolHandle_1\" etc\n# Input maps are given internal identifiers \"MapHandle_1\" etc\n# Input difference maps are given internal identifiers \"DifmapHandle_1\" etc\n#\n# The appropriate place to put output pdb files to be picked up by the system\n# is stored in the variable dropDir (see below for how to use this)\n#\n# Beware spaces...this is python after all\nfit_protein(MolHandle_1)\nwrite_pdb_file(MolHandle_1,os.path.join(dropDir,\"output.pdb\"))\n",
  STEPPED_REFINE_PROTEIN_FOR_RAMA: "# Input molecules are given internal identifiers \"MolHandle_1\" etc\n# Input maps are given internal identifiers \"MapHandle_1\" etc\n# Input difference maps are given internal identifiers \"DifmapHandle_1\" etc\n#\n# The appropriate place to put output pdb files to be picked up by the system\n# is stored in the variable dropDir (see below for how to use this)\n#\n# Beware spaces...this is python after all\nstepped_refine_protein_for_rama(MolHandle_1)\nwrite_pdb_file(MolHandle_1,os.path.join(dropDir,\"output.pdb\"))\n",
  STEPPED_REFINE_PROTEIN: "# Input molecules are given internal identifiers \"MolHandle_1\" etc\n# Input maps are given internal identifiers \"MapHandle_1\" etc\n# Input difference maps are given internal identifiers \"DifmapHandle_1\" etc\n#\n# The appropriate place to put output pdb files to be picked up by the system\n# is stored in the variable dropDir (see below for how to use this)\n#\n# Beware spaces...this is python after all\nstepped_refine_protein(MolHandle_1)\nwrite_pdb_file(MolHandle_1,os.path.join(dropDir,\"output.pdb\"))\n",
  MORPH_FIT: "# Input molecules are given internal identifiers \"MolHandle_1\" etc\n# Input maps are given internal identifiers \"MapHandle_1\" etc\n# Input difference maps are given internal identifiers \"DifmapHandle_1\" etc\n#\n# The appropriate place to put output pdb files to be picked up by the system\n# is stored in the variable dropDir (see below for how to use this)\n#\n# Beware spaces...this is python after all\ndef is_polymer_chain(imol, ch_id):\n    return is_protein_chain_qm(imol, ch_id) or is_nucleotide_chain_qm(imol, ch_id)\n\n\ndef reso_morph(imol, imol_map, n_rounds):\n    for round in range(n_rounds):\n        f = float(round)/float(n_rounds)\n        for ch_id in chain_ids(imol):\n            if is_polymer_chain(imol, ch_id):\n\n                # play with these numbers\n                radius =   6 * (2 - f)\n                sf     = 100 * (1 - f)\n                sharpen(0, sf)\n                morph_fit_chain(imol, ch_id, radius)\n\n# run the script\nreso_morph(MolHandle_1, MapHandle_1, 20)\nwrite_pdb_file(MolHandle_1,os.path.join(dropDir,\"output.pdb\"))\n",
};
