/*
 * Copyright (C) 2025-2026 Newcastle University
 * Copyright (C) 2025-2026 University of York
 *
 * This file is part of CCP4i2.
 *
 * CCP4i2 is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3,
 * modified in accordance with the provisions of the license to address
 * the requirements of UK law.
 *
 * See https://www.ccp4.ac.uk/ccp4license.php for details.
 */

import { useCallback, useMemo, useState } from "react";
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Avatar,
  Box,
  Card,
  CardContent,
  CardHeader,
  Chip,
  Stack,
  Typography,
} from "@mui/material";
import SearchField from "../search-field";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import { useApi } from "../../api";

interface TaskCategory {
  icon: string;
  title: string;
  tasks: string[];
}

const TASK_CATEGORIES: TaskCategory[] = [
  {
    icon: "data_entry",
    title: "Import merged data, AU contents, alignments or coordinates",
    tasks: [
      "import_merged",
      "ProvideAsuContents",
      "ProvideSequence",
      "ProvideAlignment",
      "AlternativeImportXIA2",
      "coordinate_selector",
      "splitMtz",
      "import_serial_pipe",
    ],
  },
  {
    icon: "data_processing",
    title: "Integrate X-ray images",
    tasks: [
      "xia2_dials",
      "xia2_xds",
      "imosflm",
      "dials_image",
      "dials_rlattice",
      "dui",
    ],
  },
  {
    icon: "data_reduction",
    title: "X-ray data reduction and analysis",
    tasks: [
      "aimless_pipe",
      "freerflag",
      "matthews",
      "molrep_selfrot",
      "AUSPEX",
      "xia2_multiplex",
      "xia2_ssx_reduce",
    ],
  },
  {
    icon: "dr_mr_modelbuild_pipeline",
    title: "Data to complete structure solution including ligand fitting",
    tasks: ["SubstituteLigand", "dr_mr_modelbuild_pipeline"],
  },
  {
    icon: "alpha_fold",
    title: "AlphaFold and RoseTTAFold Utilities",
    tasks: [
      "ccp4mg_edit_model",
      "mrparse",
      "editbfac",
      "arcimboldo",
      "slicendice",
    ],
  },
  {
    icon: "expt_phasing",
    title: "Experimental phasing",
    tasks: ["crank2", "shelx", "phaser_EP"],
  },
  {
    icon: "bioinformatics",
    title:
      "Bioinformatics including model preparation for Molecular Replacement",
    tasks: [
      "ccp4mg_edit_model",
      "ccp4mg_edit_nomrbump",
      "chainsaw",
      "sculptor",
      "phaser_ensembler",
      "clustalw",
      "findmyseq",
      "mrparse",
    ],
  },
  {
    icon: "molecular_replacement",
    title: "Molecular Replacement",
    tasks: [
      "mrbump_basic",
      "phaser_simple",
      "phaser_pipeline",
      "molrep_pipe",
      "csymmatch",
      "AMPLE",
      "SIMBAD",
      "arcimboldo",
      "comit",
      "i2Dimple",
      "morda_i2",
      "phaser_singleMR",
    ],
  },
  {
    icon: "density_modification",
    title: "Density modification",
    tasks: ["acorn", "parrot"],
  },
  {
    icon: "model_building",
    title: "Model building and Graphics",
    tasks: [
      "modelcraft",
      "coot_rebuild",
      "coot_script_lines",
      "coot_find_waters",
      "arp_warp_classic",
      "shelxeMR",
      "dr_mr_modelbuild_pipeline",
      "ccp4mg_general",
      "coot1",
      "nucleofind",
    ],
  },
  {
    icon: "refinement",
    title: "Refinement",
    tasks: [
      "servalcat_pipe",
      "prosmart_refmac",
      "ProvideTLS",
      "SubtractNative",
      "buster",
      "coot_rsr_morph",
      "lorestr_i2",
      "metalCoord",
      "pairef",
      "pdb_redo_api",
      "sheetbend",
      "zanuda",
      "phaser_rnp_pipeline",
    ],
  },
  {
    icon: "ligands",
    title: "Ligands",
    tasks: ["LidiaAcedrgNew", "MakeLink", "SubstituteLigand"],
  },
  {
    icon: "validation",
    title: "Validation and analysis",
    tasks: ["validate_protein", "edstats", "privateer", "qtpisa"],
  },
  {
    icon: "export",
    title: "Export and Deposition",
    tasks: ["adding_stats_to_mmcif_i2", "mergeMtz"],
  },
  {
    icon: "expt_data_utility",
    title: "Reflection data tools",
    tasks: [
      "pointless_reindexToMatch",
      "phaser_EP_LLG",
      "cmapcoeff",
      "chltofom",
      "cphasematch",
      "ctruncate",
      "scaleit",
      "cpatterson",
      "density_calculator",
      "freerflag",
      "matthews",
    ],
  },
  {
    icon: "model_data_utility",
    title: "Coordinate data tools",
    tasks: [
      "csymmatch",
      "gesamt",
      "coordinate_selector",
      "add_fractional_coords",
      "areaimol",
      "editbfac",
      "modelASUCheck",
      "pdbset_ui",
      "pdbview_edit",
    ],
  },
];

const DEPRECATED_TASKS: Record<string, string> = {
  PrepareDeposit: "Superseded by adding_stats_to_mmcif_i2 — do not use",
};

interface TaskInfo {
  TASKTITLE?: string;
  DESCRIPTION?: string;
  shortTitle?: string;
  isAutogenerated: boolean;
}

type TaskLookup = Record<string, TaskInfo>;

function uncategorisedCategory(lookup: TaskLookup): TaskCategory {
  const assigned = new Set<string>();
  TASK_CATEGORIES.forEach((category) => {
    category.tasks.forEach((task) => assigned.add(task));
  });
  return {
    icon: "ccp4i2",
    title: "Uncategorised (for developer use only)",
    tasks: Object.keys(lookup)
      .filter((t) => !assigned.has(t))
      .sort((a, b) => {
        const titleA = (lookup[a]?.TASKTITLE ?? a).toLowerCase();
        const titleB = (lookup[b]?.TASKTITLE ?? b).toLowerCase();
        return titleA.localeCompare(titleB);
      }),
  };
}

export function TaskChooser(props: {
  onTaskSelect: (taskName: string) => void;
}) {
  const api = useApi();
  const [searchText, setSearchText] = useState<string>("");
  const { data: taskLookup } = api.get<TaskLookup>(`task_lookup/`);

  return (
    <Stack>
      <Stack direction="row" alignItems="center" spacing={2} sx={{ p: 2 }}>
        {taskLookup && (
          <Typography>Tasks&nbsp;({Object.keys(taskLookup).length})</Typography>
        )}
        <SearchField
          value={searchText}
          onChange={setSearchText}
          placeholder="Search tasks..."
          size="small"
        />
      </Stack>
      <Box
        sx={{ flex: "auto", overflowY: "auto", p: 1, scrollbarWidth: "thin" }}
      >
        {taskLookup &&
          (searchText.trim().length > 0 ? (
            <FilteredTaskList
              taskLookup={taskLookup}
              searchText={searchText}
              onTaskSelect={props.onTaskSelect}
            />
          ) : (
            <TaskTree
              taskLookup={taskLookup}
              onTaskSelect={props.onTaskSelect}
            />
          ))}
      </Box>
    </Stack>
  );
}

function FilteredTaskList(props: {
  taskLookup: TaskLookup;
  searchText: string;
  onTaskSelect: (taskName: string) => void;
}) {
  const filteredTasks = useMemo(() => {
    return Object.keys(props.taskLookup).filter((name) => {
      const searchText = props.searchText.toUpperCase();
      if (name.toUpperCase().includes(searchText)) return true;
      const info = props.taskLookup[name];
      return (
        info.TASKTITLE?.toUpperCase().includes(searchText) ||
        info.DESCRIPTION?.toUpperCase().includes(searchText)
      );
    });
  }, [props.searchText, props.taskLookup]);

  return (
    <TaskCards
      taskLookup={props.taskLookup}
      taskNames={filteredTasks}
      onTaskSelect={props.onTaskSelect}
    />
  );
}

function TaskTree(props: {
  taskLookup: TaskLookup;
  onTaskSelect: (taskName: string) => void;
}) {
  const uncategorised = useMemo(() => {
    return uncategorisedCategory(props.taskLookup);
  }, [props.taskLookup]);

  return (
    <>
      {TASK_CATEGORIES.map((category, index) => (
        <TaskTreeFolder
          key={index}
          category={category}
          taskLookup={props.taskLookup}
          onTaskSelect={props.onTaskSelect}
        />
      ))}
      <TaskTreeFolder
        category={uncategorised}
        taskLookup={props.taskLookup}
        onTaskSelect={props.onTaskSelect}
      />
    </>
  );
}

function TaskTreeFolder(props: {
  category: TaskCategory;
  taskLookup: TaskLookup;
  onTaskSelect: (taskName: string) => void;
}) {
  return (
    <Accordion disableGutters>
      <AccordionSummary expandIcon={<ExpandMoreIcon />}>
        <Stack direction="row" alignItems="center" spacing={2}>
          <Avatar src={`/svgicons/${props.category.icon}.svg`} alt="" />
          <Typography variant="subtitle1" sx={{ fontWeight: 500 }}>
            {props.category.title}
          </Typography>
        </Stack>
      </AccordionSummary>
      <AccordionDetails>
        <TaskCards
          taskLookup={props.taskLookup}
          taskNames={props.category.tasks}
          onTaskSelect={props.onTaskSelect}
        />
      </AccordionDetails>
    </Accordion>
  );
}

function TaskCards(props: {
  taskLookup: TaskLookup;
  taskNames: string[];
  onTaskSelect: (taskName: string) => void;
}) {
  return (
    <Box
      sx={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(min(280px, 100%), 1fr))",
        gap: 2,
        p: 1,
      }}
    >
      {props.taskNames.map(
        (taskName: string) =>
          Object.keys(props.taskLookup).includes(taskName) && (
            <TaskCard
              key={taskName}
              taskName={taskName}
              task={props.taskLookup[taskName]}
              onTaskSelect={props.onTaskSelect}
            />
          ),
      )}
    </Box>
  );
}

function TaskCard(props: {
  taskName: string;
  task: any;
  onTaskSelect: (taskName: string) => void;
}) {
  const handleTaskSelect = useCallback(() => {
    if (props.task && props.onTaskSelect) {
      props.onTaskSelect(props.taskName);
    }
  }, [props.task, props.onTaskSelect]);
  return (
    <Card
      sx={{
        minHeight: "14rem",
        minWidth: "280px",
        ":hover": { boxShadow: 24, cursor: "pointer" },
      }}
      onClick={handleTaskSelect}
    >
      <CardHeader
        slotProps={{ title: { variant: "button", my: 0, py: 0 } }}
        title={
          <>
            <Avatar src={`/svgicons/${props.taskName}.svg`} alt="">
              {props.taskName?.[0]?.toUpperCase()}
            </Avatar>
            {props.task.shortTitle || props.task.TASKTITLE || props.taskName}
          </>
        }
        subheader={props.task.TASKTITLE || props.taskName}
      />
      <CardContent>
        {DEPRECATED_TASKS[props.taskName] && (
          <Chip
            label={DEPRECATED_TASKS[props.taskName]}
            size="small"
            color="error"
            variant="filled"
            sx={{ mb: 1, fontSize: "0.7rem" }}
          />
        )}
        {props.task.isAutogenerated && (
          <Chip
            label="Auto-generated Interface"
            size="small"
            color="info"
            variant="outlined"
            sx={{ mb: 1, fontSize: "0.7rem" }}
          />
        )}
        <p>{`${props.task.DESCRIPTION || ""}`}</p>
      </CardContent>
    </Card>
  );
}
