"""Which tasks' help is current: the status page, regenerated on every build.

For each task the task chooser offers (client task-chooser.tsx, in its
categories) the page is one of:

  current   its figures are captured from this app (a shots.json beside it)
  Qt        it still shows the Qt interface
  none      there is no page

conf.py calls write_status(); run directly to print the counts.
"""
import re
from pathlib import Path

DOCS = Path(__file__).resolve().parent.parent
REPO = DOCS.parent.parent
CHOOSER = REPO / "client/renderer/components/task/task-chooser.tsx"
TASK_PAGES = DOCS / "source/tasks"

# Pages whose directory is not the task's name.
ALIASES = {
    "AMPLE": "ample",
    "i2Dimple": "dimple",
    "import_serial_pipe": "import_serial",
    "add_fractional_coords": "fractional_coordinates",
    "ProvideTLS": "tls",
    "sheetbend": "shift_field",
    "qtpisa": "pisapipe",
    "phaser_ensembler": "ensemble_phaser",
    "molrep_selfrot": "srf",
    "coot_rsr_morph": "coot_refinement",
    "dials_image": "dials",
}


def chooser_categories():
    """[(category title, [task names])], as the task chooser lists them."""
    text = CHOOSER.read_text(encoding="utf-8")
    block = text[text.index("const TASK_CATEGORIES"):]
    block = block[:block.index("\n];")]
    return [(title, re.findall(r'"([^"]+)"', tasks))
            for title, tasks in re.findall(
                r'title:\s*"([^"]+)"[\s\S]*?tasks:\s*\[([^\]]*)\]', block)]


def state(task):
    page = TASK_PAGES / ALIASES.get(task, task)
    if not (page / "index.rst").exists():
        return "none", None
    return ("current" if (page / "shots.json").exists() else "Qt"), page.name


def write_status(out: Path):
    counts = {"current": 0, "Qt": 0, "none": 0}
    seen = set()
    rows = []
    for title, tasks in chooser_categories():
        rows.append(f"\n{title}\n{'-' * len(title)}\n\n"
                    ".. list-table::\n   :widths: 40 20\n\n")
        for task in tasks:
            s, page = state(task)
            if task not in seen:
                counts[s] += 1
                seen.add(task)
            name = f":doc:`{task} <tasks/{page}/index>`" if page else task
            rows.append(f"   * - {name}\n     - {s}\n")
    total = sum(counts.values())
    head = (
        "####################\n"
        "Documentation status\n"
        "####################\n\n"
        "Generated by ``tools/status.py`` on every build, from the tasks the\n"
        "task chooser offers. *current*: pictures captured from this app;\n"
        "*Qt*: the page still shows the Qt interface; *none*: no page yet.\n\n"
        f"Of {total} tasks: **{counts['current']} current**, "
        f"{counts['Qt']} Qt, {counts['none']} with no page.\n")
    out.write_text(head + "".join(rows), encoding="utf-8")
    return counts


if __name__ == "__main__":
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        print(write_status(Path(d) / "status.rst"))
