#!/usr/bin/env python3
"""Regenerate ccp4i2/requirements-runtime.txt — the CCP4-environment install lock.

The desktop app installs ccp4i2 into the user's ccp4-python with `pip install
--no-deps` (the only thing that survives those distros' corrupt dist-info, which
crashes pip's resolver). --no-deps means we must supply the full dependency
closure ourselves. This script computes that closure in a clean venv (where the
resolver works), then strips the packages CCP4 provides as ABI-native compiled
extensions — overwriting those with PyPI wheels would risk the native stack.

Usage:
    python3 -m venv /tmp/lockenv
    /tmp/lockenv/bin/pip install /path/to/ccp4i2-<ver>-py3-none-any.whl
    /tmp/lockenv/bin/python server/scripts/gen_runtime_lock.py \
        --freeze-from /tmp/lockenv > server/ccp4i2/requirements-runtime.txt

Or pass a pip-freeze file directly with --freeze-file.

Whichever way, REVIEW the diff and re-test the server ASGI import against a
target CCP4 build before committing. This script encodes policy (the exclude
list); it is not a substitute for that verification.
"""
import argparse
import subprocess
import sys

# CCP4 ships these as compiled, ABI-matched extensions (or they're job-execution
# -only and CCP4's copy is fine). Never install/overwrite them from PyPI in a
# CCP4 environment. Keep in sync with the rationale in requirements-runtime.txt.
CCP4_PROVIDED_ABI = {
    "numpy", "gemmi", "lxml", "scipy", "pandas", "rdkit",
    "cffi", "cryptography", "psutil", "biopython",
    # charset-normalizer ships an optional C speedup extension in CCP4; it is a
    # transitive dep of requests and works pure-Python, so we leave CCP4's copy
    # rather than overwrite a compiled extension for no functional gain.
    "charset-normalizer",
    # ccp4i2 itself is installed in step 1, not via the lock.
    "ccp4i2",
    # pip/setuptools/wheel are interpreter plumbing, never in the lock.
    "pip", "setuptools", "wheel",
}


# Packages a pip-freeze on ONE platform can never fully capture, because their
# requirement is guarded by an environment marker. keyring's Windows and Linux
# backends are the case in point: freeze on a Mac and both vanish, so alpha
# testers on those platforms would get keyring with no backend at all -- it
# imports, selects nothing, and credentials silently fall back to the 0600 file.
#
# These lines are appended verbatim after the frozen closure, markers intact.
# The <3.12 entries are live requirements, not no-ops: CCP4 ships Python 3.11.
# cryptography (SecretStorage's dependency) is absent by design -- it is in
# CCP4_PROVIDED_ABI above.
#
# Update these pins deliberately, alongside the pyproject dependency.
KEYCHAIN_CONDITIONAL = """
# --- OS keychain support (config/credentials.py) ---------------------------
keyring==25.7.0
jaraco.classes==3.4.0
jaraco.context==6.1.2
jaraco.functools==4.6.0
more-itertools==11.1.0
backports.tarfile==1.2.0 ; python_version < "3.12"
importlib_metadata==9.0.0 ; python_version < "3.12"
zipp==4.1.0 ; python_version < "3.12"
pywin32-ctypes==0.2.3 ; sys_platform == "win32"
SecretStorage==3.5.0 ; sys_platform == "linux"
jeepney==0.9.0 ; sys_platform == "linux"
"""

# Distributions covered by KEYCHAIN_CONDITIONAL. Dropped from the frozen lines
# so the generating platform's unmarked copy cannot shadow the marked one.
KEYCHAIN_NAMES = {
    "keyring", "jaraco.classes", "jaraco.context", "jaraco.functools",
    "more-itertools", "backports.tarfile", "importlib-metadata", "zipp",
    "pywin32-ctypes", "secretstorage", "jeepney",
}


def normalize(name: str) -> str:
    return name.lower().replace("_", "-")


def freeze(venv_dir: str) -> list[str]:
    py = f"{venv_dir}/bin/python"
    out = subprocess.check_output([py, "-m", "pip", "freeze"], text=True)
    return out.splitlines()


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--freeze-from", help="venv dir to pip-freeze")
    g.add_argument("--freeze-file", help="existing pip-freeze output file")
    args = ap.parse_args()

    if args.freeze_from:
        lines = freeze(args.freeze_from)
    else:
        with open(args.freeze_file) as f:
            lines = f.read().splitlines()

    kept = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#") or "==" not in line:
            continue
        name = normalize(line.split("==", 1)[0])
        if name in {normalize(n) for n in CCP4_PROVIDED_ABI}:
            continue
        if name in {normalize(n) for n in KEYCHAIN_NAMES}:
            continue  # re-emitted below, with its environment markers
        kept.append(line)

    print("# AUTO-GENERATED by scripts/gen_runtime_lock.py — review before commit.")
    print("# CCP4-provided ABI-native packages are excluded; see the committed")
    print("# requirements-runtime.txt header for the full rationale.")
    for line in sorted(kept, key=lambda s: normalize(s)):
        print(line)
    print(KEYCHAIN_CONDITIONAL, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
