# Generated by Django 5.0.6 on 2025-01-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccp4x", "0003_data_migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttag",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="ccp4x.project"
            ),
        ),
    ]
