# Generated by Django 4.2.18 on 2025-02-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4x', '0005_alter_file_directory_alter_fileuse_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcharvalue',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_values', to='ccp4x.job'),
        ),
        migrations.AlterField(
            model_name='jobfloatvalue',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ccp4x.jobvaluekey'),
        ),
    ]
