# Generated by Django 3.2.25 on 2025-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4x', '0008_projectgroup_projectgroupmembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='tags', to='ccp4x.Project'),
        ),
    ]
