# Generated by Django 5.2.17 on 2026-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4i2', '0017_projecttag_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimport',
            name='source_checksum',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
