# Generated by Django 5.2.15 on 2026-09-16 21:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4i2', '0022_jobinteractivesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('staging', 'staging'), ('ready', 'ready'), ('consumed', 'consumed')], default='staging', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'state'], name='ccp4i2_stag_owner_e62e7c_idx')],
            },
        ),
    ]
