# Generated by Django 5.2.17 on 2026-09-20 11:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_sites_out_of_json(apps, schema_editor):
    """Copy each campaign's JSON sites into CampaignSite rows.

    Order in the list becomes ``order``, so the UI list is unchanged after the
    migration. A site with no usable origin is skipped rather than guessed at:
    the origin is the whole point of a site, and inventing one would put a
    marker somewhere misleading.

    Names are made unique within a group (the new table constrains them, the
    JSON list did not), by suffixing duplicates.
    """
    ProjectGroup = apps.get_model("ccp4i2", "ProjectGroup")
    CampaignSite = apps.get_model("ccp4i2", "CampaignSite")

    for group in ProjectGroup.objects.exclude(sites=[]).iterator():
        seen = set()
        for order, site in enumerate(group.sites or []):
            if not isinstance(site, dict):
                continue
            origin = site.get("origin")
            if not isinstance(origin, (list, tuple)) or len(origin) != 3:
                continue
            try:
                x, y, z = (float(v) for v in origin)
            except (TypeError, ValueError):
                continue

            name = str(site.get("name") or "Site %d" % (order + 1))[:100]
            if name in seen:
                suffix = 2
                while "%s (%d)" % (name[:94], suffix) in seen:
                    suffix += 1
                name = "%s (%d)" % (name[:94], suffix)
            seen.add(name)

            quat = site.get("quat")
            if not (isinstance(quat, (list, tuple)) and len(quat) == 4):
                quat = None

            zoom = site.get("zoom")
            try:
                zoom = float(zoom) if zoom is not None else None
            except (TypeError, ValueError):
                zoom = None

            CampaignSite.objects.create(
                group=group,
                name=name,
                origin_x=x, origin_y=y, origin_z=z,
                quat=list(quat) if quat else None,
                zoom=zoom,
                order=order,
            )


def migrate_sites_back_to_json(apps, schema_editor):
    """Reverse: rebuild the JSON list from the rows, so 0024 is reversible."""
    ProjectGroup = apps.get_model("ccp4i2", "ProjectGroup")
    CampaignSite = apps.get_model("ccp4i2", "CampaignSite")

    for group in ProjectGroup.objects.iterator():
        sites = []
        for site in CampaignSite.objects.filter(group=group).order_by("order", "id"):
            entry = {
                "name": site.name,
                "origin": [site.origin_x, site.origin_y, site.origin_z],
            }
            if site.quat:
                entry["quat"] = site.quat
            if site.zoom is not None:
                entry["zoom"] = site.zoom
            sites.append(entry)
        group.sites = sites
        group.save(update_fields=["sites"])


class Migration(migrations.Migration):

    dependencies = [
        ('ccp4i2', '0023_stagedupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin_x', models.FloatField()),
                ('origin_y', models.FloatField()),
                ('origin_z', models.FloatField()),
                ('quat', models.JSONField(blank=True, null=True)),
                ('zoom', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('hit', 'Ligand present'), ('empty', 'No ligand'), ('unclear', 'Unclear')], max_length=16)),
                ('evaluator', models.CharField(blank=True, default='', max_length=150)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddConstraint(
            model_name='projectgroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'parent')), fields=('group',), name='one_parent_per_group'),
        ),
        migrations.AddField(
            model_name='campaignsite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_set', to='ccp4i2.projectgroup'),
        ),
        migrations.AddField(
            model_name='siteevaluation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_evaluations', to='ccp4i2.project'),
        ),
        migrations.AddField(
            model_name='siteevaluation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ccp4i2.campaignsite'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignsite',
            unique_together={('group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='siteevaluation',
            unique_together={('project', 'site')},
        ),
        # The data step comes after EVERY schema operation on the new tables
        # and before the one that drops the column it reads. As released in
        # 3.1.0a71 it sat straight after the CreateModels, ahead of the AddField
        # that gives CampaignSite its group, so it raised "CampaignSite() got
        # unexpected keyword arguments: 'group'" on any database that had a
        # campaign with sites -- and on no other, which is how it got out.
        #
        # The data step sees the historical model as of its position in this
        # list, so the rule is: finish the tables, then fill them. (Moving up
        # only that one AddField also works, on SQLite and PostgreSQL alike;
        # this order just leaves nothing to reason about.)
        #
        # Reordering a released migration is safe here because the schema it
        # arrives at is unchanged: a database that already applied 0024 (one
        # with no sites) is exactly where this version would have left it.
        migrations.RunPython(
            migrate_sites_out_of_json, migrate_sites_back_to_json
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='sites',
        ),
    ]
